// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: ap_common_types.proto
// Original file comments:
// @file
// @brief System definitions for all of the access point proto files.
//
// ---------------------------------------------------------------------
// Copyright (c) 2016 by Cisco Systems, Inc.
// All rights reserved.
// ---------------------------------------------------------------------
//
//
//
// @defgroup System
// @brief System AP definitions and Global initializations.
//
#ifndef GRPC_ap_5fcommon_5ftypes_2eproto__INCLUDED
#define GRPC_ap_5fcommon_5ftypes_2eproto__INCLUDED

#include "ap_common_types.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace cheetah {

}  // namespace cheetah


#endif  // GRPC_ap_5fcommon_5ftypes_2eproto__INCLUDED
