// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_global.proto

#ifndef PROTOBUF_ap_5fglobal_2eproto__INCLUDED
#define PROTOBUF_ap_5fglobal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ap_common_types.pb.h"
// @@protoc_insertion_point(includes)

namespace cheetah {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ap_5fglobal_2eproto();
void protobuf_InitDefaults_ap_5fglobal_2eproto();
void protobuf_AssignDesc_ap_5fglobal_2eproto();
void protobuf_ShutdownFile_ap_5fglobal_2eproto();

class APCfgMsgRsp;
class APGlobalNotif;
class APGlobalsGetMsg;
class APGlobalsGetMsgRsp;
class APInitMsg;
class APInitMsgRsp;

enum APGlobalNotifType {
  AP_GLOBAL_EVENT_TYPE_RESERVED = 0,
  AP_GLOBAL_EVENT_TYPE_ERROR = 1,
  AP_GLOBAL_EVENT_TYPE_HEARTBEAT = 2,
  AP_GLOBAL_EVENT_TYPE_VERSION = 3,
  AP_GLOBAL_EVENT_TYPE_CONFIG = 4,
  APGlobalNotifType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APGlobalNotifType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APGlobalNotifType_IsValid(int value);
const APGlobalNotifType APGlobalNotifType_MIN = AP_GLOBAL_EVENT_TYPE_RESERVED;
const APGlobalNotifType APGlobalNotifType_MAX = AP_GLOBAL_EVENT_TYPE_CONFIG;
const int APGlobalNotifType_ARRAYSIZE = APGlobalNotifType_MAX + 1;

const ::google::protobuf::EnumDescriptor* APGlobalNotifType_descriptor();
inline const ::std::string& APGlobalNotifType_Name(APGlobalNotifType value) {
  return ::google::protobuf::internal::NameOfEnum(
    APGlobalNotifType_descriptor(), value);
}
inline bool APGlobalNotifType_Parse(
    const ::std::string& name, APGlobalNotifType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APGlobalNotifType>(
    APGlobalNotifType_descriptor(), name, value);
}
// ===================================================================

class APInitMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APInitMsg) */ {
 public:
  APInitMsg();
  virtual ~APInitMsg();

  APInitMsg(const APInitMsg& from);

  inline APInitMsg& operator=(const APInitMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APInitMsg& default_instance();

  static const APInitMsg* internal_default_instance();

  void Swap(APInitMsg* other);

  // implements Message ----------------------------------------------

  inline APInitMsg* New() const { return New(NULL); }

  APInitMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APInitMsg& from);
  void MergeFrom(const APInitMsg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APInitMsg* other);
  void UnsafeMergeFrom(const APInitMsg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 MajorVer = 1;
  void clear_majorver();
  static const int kMajorVerFieldNumber = 1;
  ::google::protobuf::uint32 majorver() const;
  void set_majorver(::google::protobuf::uint32 value);

  // optional uint32 MinorVer = 2;
  void clear_minorver();
  static const int kMinorVerFieldNumber = 2;
  ::google::protobuf::uint32 minorver() const;
  void set_minorver(::google::protobuf::uint32 value);

  // optional uint32 SubVer = 3;
  void clear_subver();
  static const int kSubVerFieldNumber = 3;
  ::google::protobuf::uint32 subver() const;
  void set_subver(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cheetah.APInitMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 majorver_;
  ::google::protobuf::uint32 minorver_;
  ::google::protobuf::uint32 subver_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APInitMsg> APInitMsg_default_instance_;

// -------------------------------------------------------------------

class APInitMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APInitMsgRsp) */ {
 public:
  APInitMsgRsp();
  virtual ~APInitMsgRsp();

  APInitMsgRsp(const APInitMsgRsp& from);

  inline APInitMsgRsp& operator=(const APInitMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APInitMsgRsp& default_instance();

  static const APInitMsgRsp* internal_default_instance();

  void Swap(APInitMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APInitMsgRsp* New() const { return New(NULL); }

  APInitMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APInitMsgRsp& from);
  void MergeFrom(const APInitMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APInitMsgRsp* other);
  void UnsafeMergeFrom(const APInitMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 MajorVer = 1;
  void clear_majorver();
  static const int kMajorVerFieldNumber = 1;
  ::google::protobuf::uint32 majorver() const;
  void set_majorver(::google::protobuf::uint32 value);

  // optional uint32 MinorVer = 2;
  void clear_minorver();
  static const int kMinorVerFieldNumber = 2;
  ::google::protobuf::uint32 minorver() const;
  void set_minorver(::google::protobuf::uint32 value);

  // optional uint32 SubVer = 3;
  void clear_subver();
  static const int kSubVerFieldNumber = 3;
  ::google::protobuf::uint32 subver() const;
  void set_subver(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cheetah.APInitMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 majorver_;
  ::google::protobuf::uint32 minorver_;
  ::google::protobuf::uint32 subver_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APInitMsgRsp> APInitMsgRsp_default_instance_;

// -------------------------------------------------------------------

class APCfgMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APCfgMsgRsp) */ {
 public:
  APCfgMsgRsp();
  virtual ~APCfgMsgRsp();

  APCfgMsgRsp(const APCfgMsgRsp& from);

  inline APCfgMsgRsp& operator=(const APCfgMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APCfgMsgRsp& default_instance();

  static const APCfgMsgRsp* internal_default_instance();

  void Swap(APCfgMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APCfgMsgRsp* New() const { return New(NULL); }

  APCfgMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APCfgMsgRsp& from);
  void MergeFrom(const APCfgMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APCfgMsgRsp* other);
  void UnsafeMergeFrom(const APCfgMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string Token = 1;
  void clear_token();
  static const int kTokenFieldNumber = 1;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // optional string ProxyURL = 2;
  void clear_proxyurl();
  static const int kProxyURLFieldNumber = 2;
  const ::std::string& proxyurl() const;
  void set_proxyurl(const ::std::string& value);
  void set_proxyurl(const char* value);
  void set_proxyurl(const char* value, size_t size);
  ::std::string* mutable_proxyurl();
  ::std::string* release_proxyurl();
  void set_allocated_proxyurl(::std::string* proxyurl);

  // optional uint32 ProxyPort = 3;
  void clear_proxyport();
  static const int kProxyPortFieldNumber = 3;
  ::google::protobuf::uint32 proxyport() const;
  void set_proxyport(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cheetah.APCfgMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  ::google::protobuf::internal::ArenaStringPtr proxyurl_;
  ::google::protobuf::uint32 proxyport_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APCfgMsgRsp> APCfgMsgRsp_default_instance_;

// -------------------------------------------------------------------

class APGlobalNotif : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APGlobalNotif) */ {
 public:
  APGlobalNotif();
  virtual ~APGlobalNotif();

  APGlobalNotif(const APGlobalNotif& from);

  inline APGlobalNotif& operator=(const APGlobalNotif& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APGlobalNotif& default_instance();

  enum EventCase {
    kInitRspMsg = 3,
    kCfgRspMsg = 4,
    EVENT_NOT_SET = 0,
  };

  static const APGlobalNotif* internal_default_instance();

  void Swap(APGlobalNotif* other);

  // implements Message ----------------------------------------------

  inline APGlobalNotif* New() const { return New(NULL); }

  APGlobalNotif* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APGlobalNotif& from);
  void MergeFrom(const APGlobalNotif& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APGlobalNotif* other);
  void UnsafeMergeFrom(const APGlobalNotif& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APGlobalNotifType EventType = 1;
  void clear_eventtype();
  static const int kEventTypeFieldNumber = 1;
  ::cheetah::APGlobalNotifType eventtype() const;
  void set_eventtype(::cheetah::APGlobalNotifType value);

  // optional .cheetah.APErrorStatus ErrStatus = 2;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 2;
  const ::cheetah::APErrorStatus& errstatus() const;
  ::cheetah::APErrorStatus* mutable_errstatus();
  ::cheetah::APErrorStatus* release_errstatus();
  void set_allocated_errstatus(::cheetah::APErrorStatus* errstatus);

  // optional .cheetah.APInitMsgRsp InitRspMsg = 3;
  bool has_initrspmsg() const;
  void clear_initrspmsg();
  static const int kInitRspMsgFieldNumber = 3;
  const ::cheetah::APInitMsgRsp& initrspmsg() const;
  ::cheetah::APInitMsgRsp* mutable_initrspmsg();
  ::cheetah::APInitMsgRsp* release_initrspmsg();
  void set_allocated_initrspmsg(::cheetah::APInitMsgRsp* initrspmsg);

  // optional .cheetah.APCfgMsgRsp CfgRspMsg = 4;
  bool has_cfgrspmsg() const;
  void clear_cfgrspmsg();
  static const int kCfgRspMsgFieldNumber = 4;
  const ::cheetah::APCfgMsgRsp& cfgrspmsg() const;
  ::cheetah::APCfgMsgRsp* mutable_cfgrspmsg();
  ::cheetah::APCfgMsgRsp* release_cfgrspmsg();
  void set_allocated_cfgrspmsg(::cheetah::APCfgMsgRsp* cfgrspmsg);

  EventCase Event_case() const;
  // @@protoc_insertion_point(class_scope:cheetah.APGlobalNotif)
 private:
  inline void set_has_initrspmsg();
  inline void set_has_cfgrspmsg();

  inline bool has_Event() const;
  void clear_Event();
  inline void clear_has_Event();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cheetah::APErrorStatus* errstatus_;
  int eventtype_;
  union EventUnion {
    EventUnion() {}
    ::cheetah::APInitMsgRsp* initrspmsg_;
    ::cheetah::APCfgMsgRsp* cfgrspmsg_;
  } Event_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APGlobalNotif> APGlobalNotif_default_instance_;

// -------------------------------------------------------------------

class APGlobalsGetMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APGlobalsGetMsg) */ {
 public:
  APGlobalsGetMsg();
  virtual ~APGlobalsGetMsg();

  APGlobalsGetMsg(const APGlobalsGetMsg& from);

  inline APGlobalsGetMsg& operator=(const APGlobalsGetMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APGlobalsGetMsg& default_instance();

  static const APGlobalsGetMsg* internal_default_instance();

  void Swap(APGlobalsGetMsg* other);

  // implements Message ----------------------------------------------

  inline APGlobalsGetMsg* New() const { return New(NULL); }

  APGlobalsGetMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APGlobalsGetMsg& from);
  void MergeFrom(const APGlobalsGetMsg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APGlobalsGetMsg* other);
  void UnsafeMergeFrom(const APGlobalsGetMsg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cheetah.APGlobalsGetMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APGlobalsGetMsg> APGlobalsGetMsg_default_instance_;

// -------------------------------------------------------------------

class APGlobalsGetMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APGlobalsGetMsgRsp) */ {
 public:
  APGlobalsGetMsgRsp();
  virtual ~APGlobalsGetMsgRsp();

  APGlobalsGetMsgRsp(const APGlobalsGetMsgRsp& from);

  inline APGlobalsGetMsgRsp& operator=(const APGlobalsGetMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APGlobalsGetMsgRsp& default_instance();

  static const APGlobalsGetMsgRsp* internal_default_instance();

  void Swap(APGlobalsGetMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APGlobalsGetMsgRsp* New() const { return New(NULL); }

  APGlobalsGetMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APGlobalsGetMsgRsp& from);
  void MergeFrom(const APGlobalsGetMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APGlobalsGetMsgRsp* other);
  void UnsafeMergeFrom(const APGlobalsGetMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APErrorStatus ErrStatus = 1;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 1;
  const ::cheetah::APErrorStatus& errstatus() const;
  ::cheetah::APErrorStatus* mutable_errstatus();
  ::cheetah::APErrorStatus* release_errstatus();
  void set_allocated_errstatus(::cheetah::APErrorStatus* errstatus);

  // optional uint32 MaxRadioNameLength = 2;
  void clear_maxradionamelength();
  static const int kMaxRadioNameLengthFieldNumber = 2;
  ::google::protobuf::uint32 maxradionamelength() const;
  void set_maxradionamelength(::google::protobuf::uint32 value);

  // optional uint32 MaxSsidNameLength = 3;
  void clear_maxssidnamelength();
  static const int kMaxSsidNameLengthFieldNumber = 3;
  ::google::protobuf::uint32 maxssidnamelength() const;
  void set_maxssidnamelength(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cheetah.APGlobalsGetMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cheetah::APErrorStatus* errstatus_;
  ::google::protobuf::uint32 maxradionamelength_;
  ::google::protobuf::uint32 maxssidnamelength_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fglobal_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fglobal_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fglobal_2eproto();
  friend void protobuf_ShutdownFile_ap_5fglobal_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APGlobalsGetMsgRsp> APGlobalsGetMsgRsp_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// APInitMsg

// optional uint32 MajorVer = 1;
inline void APInitMsg::clear_majorver() {
  majorver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsg::majorver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsg.MajorVer)
  return majorver_;
}
inline void APInitMsg::set_majorver(::google::protobuf::uint32 value) {
  
  majorver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsg.MajorVer)
}

// optional uint32 MinorVer = 2;
inline void APInitMsg::clear_minorver() {
  minorver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsg::minorver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsg.MinorVer)
  return minorver_;
}
inline void APInitMsg::set_minorver(::google::protobuf::uint32 value) {
  
  minorver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsg.MinorVer)
}

// optional uint32 SubVer = 3;
inline void APInitMsg::clear_subver() {
  subver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsg::subver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsg.SubVer)
  return subver_;
}
inline void APInitMsg::set_subver(::google::protobuf::uint32 value) {
  
  subver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsg.SubVer)
}

inline const APInitMsg* APInitMsg::internal_default_instance() {
  return &APInitMsg_default_instance_.get();
}
// -------------------------------------------------------------------

// APInitMsgRsp

// optional uint32 MajorVer = 1;
inline void APInitMsgRsp::clear_majorver() {
  majorver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsgRsp::majorver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsgRsp.MajorVer)
  return majorver_;
}
inline void APInitMsgRsp::set_majorver(::google::protobuf::uint32 value) {
  
  majorver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsgRsp.MajorVer)
}

// optional uint32 MinorVer = 2;
inline void APInitMsgRsp::clear_minorver() {
  minorver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsgRsp::minorver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsgRsp.MinorVer)
  return minorver_;
}
inline void APInitMsgRsp::set_minorver(::google::protobuf::uint32 value) {
  
  minorver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsgRsp.MinorVer)
}

// optional uint32 SubVer = 3;
inline void APInitMsgRsp::clear_subver() {
  subver_ = 0u;
}
inline ::google::protobuf::uint32 APInitMsgRsp::subver() const {
  // @@protoc_insertion_point(field_get:cheetah.APInitMsgRsp.SubVer)
  return subver_;
}
inline void APInitMsgRsp::set_subver(::google::protobuf::uint32 value) {
  
  subver_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APInitMsgRsp.SubVer)
}

inline const APInitMsgRsp* APInitMsgRsp::internal_default_instance() {
  return &APInitMsgRsp_default_instance_.get();
}
// -------------------------------------------------------------------

// APCfgMsgRsp

// optional string Token = 1;
inline void APCfgMsgRsp::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& APCfgMsgRsp::token() const {
  // @@protoc_insertion_point(field_get:cheetah.APCfgMsgRsp.Token)
  return token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APCfgMsgRsp::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cheetah.APCfgMsgRsp.Token)
}
inline void APCfgMsgRsp::set_token(const char* value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cheetah.APCfgMsgRsp.Token)
}
inline void APCfgMsgRsp::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cheetah.APCfgMsgRsp.Token)
}
inline ::std::string* APCfgMsgRsp::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:cheetah.APCfgMsgRsp.Token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APCfgMsgRsp::release_token() {
  // @@protoc_insertion_point(field_release:cheetah.APCfgMsgRsp.Token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APCfgMsgRsp::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:cheetah.APCfgMsgRsp.Token)
}

// optional string ProxyURL = 2;
inline void APCfgMsgRsp::clear_proxyurl() {
  proxyurl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& APCfgMsgRsp::proxyurl() const {
  // @@protoc_insertion_point(field_get:cheetah.APCfgMsgRsp.ProxyURL)
  return proxyurl_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APCfgMsgRsp::set_proxyurl(const ::std::string& value) {
  
  proxyurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cheetah.APCfgMsgRsp.ProxyURL)
}
inline void APCfgMsgRsp::set_proxyurl(const char* value) {
  
  proxyurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cheetah.APCfgMsgRsp.ProxyURL)
}
inline void APCfgMsgRsp::set_proxyurl(const char* value, size_t size) {
  
  proxyurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cheetah.APCfgMsgRsp.ProxyURL)
}
inline ::std::string* APCfgMsgRsp::mutable_proxyurl() {
  
  // @@protoc_insertion_point(field_mutable:cheetah.APCfgMsgRsp.ProxyURL)
  return proxyurl_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APCfgMsgRsp::release_proxyurl() {
  // @@protoc_insertion_point(field_release:cheetah.APCfgMsgRsp.ProxyURL)
  
  return proxyurl_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APCfgMsgRsp::set_allocated_proxyurl(::std::string* proxyurl) {
  if (proxyurl != NULL) {
    
  } else {
    
  }
  proxyurl_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), proxyurl);
  // @@protoc_insertion_point(field_set_allocated:cheetah.APCfgMsgRsp.ProxyURL)
}

// optional uint32 ProxyPort = 3;
inline void APCfgMsgRsp::clear_proxyport() {
  proxyport_ = 0u;
}
inline ::google::protobuf::uint32 APCfgMsgRsp::proxyport() const {
  // @@protoc_insertion_point(field_get:cheetah.APCfgMsgRsp.ProxyPort)
  return proxyport_;
}
inline void APCfgMsgRsp::set_proxyport(::google::protobuf::uint32 value) {
  
  proxyport_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APCfgMsgRsp.ProxyPort)
}

inline const APCfgMsgRsp* APCfgMsgRsp::internal_default_instance() {
  return &APCfgMsgRsp_default_instance_.get();
}
// -------------------------------------------------------------------

// APGlobalNotif

// optional .cheetah.APGlobalNotifType EventType = 1;
inline void APGlobalNotif::clear_eventtype() {
  eventtype_ = 0;
}
inline ::cheetah::APGlobalNotifType APGlobalNotif::eventtype() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalNotif.EventType)
  return static_cast< ::cheetah::APGlobalNotifType >(eventtype_);
}
inline void APGlobalNotif::set_eventtype(::cheetah::APGlobalNotifType value) {
  
  eventtype_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APGlobalNotif.EventType)
}

// optional .cheetah.APErrorStatus ErrStatus = 2;
inline bool APGlobalNotif::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline void APGlobalNotif::clear_errstatus() {
  if (GetArenaNoVirtual() == NULL && errstatus_ != NULL) delete errstatus_;
  errstatus_ = NULL;
}
inline const ::cheetah::APErrorStatus& APGlobalNotif::errstatus() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalNotif.ErrStatus)
  return errstatus_ != NULL ? *errstatus_
                         : *::cheetah::APErrorStatus::internal_default_instance();
}
inline ::cheetah::APErrorStatus* APGlobalNotif::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::cheetah::APErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APGlobalNotif.ErrStatus)
  return errstatus_;
}
inline ::cheetah::APErrorStatus* APGlobalNotif::release_errstatus() {
  // @@protoc_insertion_point(field_release:cheetah.APGlobalNotif.ErrStatus)
  
  ::cheetah::APErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline void APGlobalNotif::set_allocated_errstatus(::cheetah::APErrorStatus* errstatus) {
  delete errstatus_;
  errstatus_ = errstatus;
  if (errstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APGlobalNotif.ErrStatus)
}

// optional .cheetah.APInitMsgRsp InitRspMsg = 3;
inline bool APGlobalNotif::has_initrspmsg() const {
  return Event_case() == kInitRspMsg;
}
inline void APGlobalNotif::set_has_initrspmsg() {
  _oneof_case_[0] = kInitRspMsg;
}
inline void APGlobalNotif::clear_initrspmsg() {
  if (has_initrspmsg()) {
    delete Event_.initrspmsg_;
    clear_has_Event();
  }
}
inline  const ::cheetah::APInitMsgRsp& APGlobalNotif::initrspmsg() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalNotif.InitRspMsg)
  return has_initrspmsg()
      ? *Event_.initrspmsg_
      : ::cheetah::APInitMsgRsp::default_instance();
}
inline ::cheetah::APInitMsgRsp* APGlobalNotif::mutable_initrspmsg() {
  if (!has_initrspmsg()) {
    clear_Event();
    set_has_initrspmsg();
    Event_.initrspmsg_ = new ::cheetah::APInitMsgRsp;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APGlobalNotif.InitRspMsg)
  return Event_.initrspmsg_;
}
inline ::cheetah::APInitMsgRsp* APGlobalNotif::release_initrspmsg() {
  // @@protoc_insertion_point(field_release:cheetah.APGlobalNotif.InitRspMsg)
  if (has_initrspmsg()) {
    clear_has_Event();
    ::cheetah::APInitMsgRsp* temp = Event_.initrspmsg_;
    Event_.initrspmsg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void APGlobalNotif::set_allocated_initrspmsg(::cheetah::APInitMsgRsp* initrspmsg) {
  clear_Event();
  if (initrspmsg) {
    set_has_initrspmsg();
    Event_.initrspmsg_ = initrspmsg;
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APGlobalNotif.InitRspMsg)
}

// optional .cheetah.APCfgMsgRsp CfgRspMsg = 4;
inline bool APGlobalNotif::has_cfgrspmsg() const {
  return Event_case() == kCfgRspMsg;
}
inline void APGlobalNotif::set_has_cfgrspmsg() {
  _oneof_case_[0] = kCfgRspMsg;
}
inline void APGlobalNotif::clear_cfgrspmsg() {
  if (has_cfgrspmsg()) {
    delete Event_.cfgrspmsg_;
    clear_has_Event();
  }
}
inline  const ::cheetah::APCfgMsgRsp& APGlobalNotif::cfgrspmsg() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalNotif.CfgRspMsg)
  return has_cfgrspmsg()
      ? *Event_.cfgrspmsg_
      : ::cheetah::APCfgMsgRsp::default_instance();
}
inline ::cheetah::APCfgMsgRsp* APGlobalNotif::mutable_cfgrspmsg() {
  if (!has_cfgrspmsg()) {
    clear_Event();
    set_has_cfgrspmsg();
    Event_.cfgrspmsg_ = new ::cheetah::APCfgMsgRsp;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APGlobalNotif.CfgRspMsg)
  return Event_.cfgrspmsg_;
}
inline ::cheetah::APCfgMsgRsp* APGlobalNotif::release_cfgrspmsg() {
  // @@protoc_insertion_point(field_release:cheetah.APGlobalNotif.CfgRspMsg)
  if (has_cfgrspmsg()) {
    clear_has_Event();
    ::cheetah::APCfgMsgRsp* temp = Event_.cfgrspmsg_;
    Event_.cfgrspmsg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void APGlobalNotif::set_allocated_cfgrspmsg(::cheetah::APCfgMsgRsp* cfgrspmsg) {
  clear_Event();
  if (cfgrspmsg) {
    set_has_cfgrspmsg();
    Event_.cfgrspmsg_ = cfgrspmsg;
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APGlobalNotif.CfgRspMsg)
}

inline bool APGlobalNotif::has_Event() const {
  return Event_case() != EVENT_NOT_SET;
}
inline void APGlobalNotif::clear_has_Event() {
  _oneof_case_[0] = EVENT_NOT_SET;
}
inline APGlobalNotif::EventCase APGlobalNotif::Event_case() const {
  return APGlobalNotif::EventCase(_oneof_case_[0]);
}
inline const APGlobalNotif* APGlobalNotif::internal_default_instance() {
  return &APGlobalNotif_default_instance_.get();
}
// -------------------------------------------------------------------

// APGlobalsGetMsg

inline const APGlobalsGetMsg* APGlobalsGetMsg::internal_default_instance() {
  return &APGlobalsGetMsg_default_instance_.get();
}
// -------------------------------------------------------------------

// APGlobalsGetMsgRsp

// optional .cheetah.APErrorStatus ErrStatus = 1;
inline bool APGlobalsGetMsgRsp::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline void APGlobalsGetMsgRsp::clear_errstatus() {
  if (GetArenaNoVirtual() == NULL && errstatus_ != NULL) delete errstatus_;
  errstatus_ = NULL;
}
inline const ::cheetah::APErrorStatus& APGlobalsGetMsgRsp::errstatus() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalsGetMsgRsp.ErrStatus)
  return errstatus_ != NULL ? *errstatus_
                         : *::cheetah::APErrorStatus::internal_default_instance();
}
inline ::cheetah::APErrorStatus* APGlobalsGetMsgRsp::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::cheetah::APErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APGlobalsGetMsgRsp.ErrStatus)
  return errstatus_;
}
inline ::cheetah::APErrorStatus* APGlobalsGetMsgRsp::release_errstatus() {
  // @@protoc_insertion_point(field_release:cheetah.APGlobalsGetMsgRsp.ErrStatus)
  
  ::cheetah::APErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline void APGlobalsGetMsgRsp::set_allocated_errstatus(::cheetah::APErrorStatus* errstatus) {
  delete errstatus_;
  errstatus_ = errstatus;
  if (errstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APGlobalsGetMsgRsp.ErrStatus)
}

// optional uint32 MaxRadioNameLength = 2;
inline void APGlobalsGetMsgRsp::clear_maxradionamelength() {
  maxradionamelength_ = 0u;
}
inline ::google::protobuf::uint32 APGlobalsGetMsgRsp::maxradionamelength() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalsGetMsgRsp.MaxRadioNameLength)
  return maxradionamelength_;
}
inline void APGlobalsGetMsgRsp::set_maxradionamelength(::google::protobuf::uint32 value) {
  
  maxradionamelength_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APGlobalsGetMsgRsp.MaxRadioNameLength)
}

// optional uint32 MaxSsidNameLength = 3;
inline void APGlobalsGetMsgRsp::clear_maxssidnamelength() {
  maxssidnamelength_ = 0u;
}
inline ::google::protobuf::uint32 APGlobalsGetMsgRsp::maxssidnamelength() const {
  // @@protoc_insertion_point(field_get:cheetah.APGlobalsGetMsgRsp.MaxSsidNameLength)
  return maxssidnamelength_;
}
inline void APGlobalsGetMsgRsp::set_maxssidnamelength(::google::protobuf::uint32 value) {
  
  maxssidnamelength_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APGlobalsGetMsgRsp.MaxSsidNameLength)
}

inline const APGlobalsGetMsgRsp* APGlobalsGetMsgRsp::internal_default_instance() {
  return &APGlobalsGetMsgRsp_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cheetah

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cheetah::APGlobalNotifType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APGlobalNotifType>() {
  return ::cheetah::APGlobalNotifType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ap_5fglobal_2eproto__INCLUDED
