// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_packet.proto

#ifndef PROTOBUF_ap_5fpacket_2eproto__INCLUDED
#define PROTOBUF_ap_5fpacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ap_common_types.pb.h"
// @@protoc_insertion_point(includes)

namespace access_point {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ap_5fpacket_2eproto();
void protobuf_InitDefaults_ap_5fpacket_2eproto();
void protobuf_AssignDesc_ap_5fpacket_2eproto();
void protobuf_ShutdownFile_ap_5fpacket_2eproto();

class APPacketHdr;
class APPacketsMsg;
class APPacketsMsgRsp;

enum APMsgType {
  AP_MSG_TYPE_RESERVED = 0,
  AP_MSG_TYPE_MGMT = 1,
  AP_MSG_TYPE_CTRL = 2,
  AP_MSG_TYPE_DATA = 3,
  AP_MSG_TYPE_CISCO = 4,
  APMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APMsgType_IsValid(int value);
const APMsgType APMsgType_MIN = AP_MSG_TYPE_RESERVED;
const APMsgType APMsgType_MAX = AP_MSG_TYPE_CISCO;
const int APMsgType_ARRAYSIZE = APMsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* APMsgType_descriptor();
inline const ::std::string& APMsgType_Name(APMsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    APMsgType_descriptor(), value);
}
inline bool APMsgType_Parse(
    const ::std::string& name, APMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APMsgType>(
    APMsgType_descriptor(), name, value);
}
enum APMgmtMsgSubtype {
  AP_MGMT_MSG_SUBTYPE_RESERVED = 0,
  AP_MGMT_MSG_SUBTYPE_ASSOC = 1,
  AP_MGMT_MSG_SUBTYPE_AUTH = 2,
  AP_MGMT_MSG_SUBTYPE_PROBE = 4,
  AP_MGMT_MSG_SUBTYPE_ALL = 65535,
  APMgmtMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APMgmtMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APMgmtMsgSubtype_IsValid(int value);
const APMgmtMsgSubtype APMgmtMsgSubtype_MIN = AP_MGMT_MSG_SUBTYPE_RESERVED;
const APMgmtMsgSubtype APMgmtMsgSubtype_MAX = AP_MGMT_MSG_SUBTYPE_ALL;
const int APMgmtMsgSubtype_ARRAYSIZE = APMgmtMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APMgmtMsgSubtype_descriptor();
inline const ::std::string& APMgmtMsgSubtype_Name(APMgmtMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APMgmtMsgSubtype_descriptor(), value);
}
inline bool APMgmtMsgSubtype_Parse(
    const ::std::string& name, APMgmtMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APMgmtMsgSubtype>(
    APMgmtMsgSubtype_descriptor(), name, value);
}
enum APCtrlMsgSubtype {
  AP_CTRL_MSG_SUBTYPE_RESERVED = 0,
  AP_CTRL_MSG_SUBTYPE_ALL = 65535,
  APCtrlMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APCtrlMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APCtrlMsgSubtype_IsValid(int value);
const APCtrlMsgSubtype APCtrlMsgSubtype_MIN = AP_CTRL_MSG_SUBTYPE_RESERVED;
const APCtrlMsgSubtype APCtrlMsgSubtype_MAX = AP_CTRL_MSG_SUBTYPE_ALL;
const int APCtrlMsgSubtype_ARRAYSIZE = APCtrlMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APCtrlMsgSubtype_descriptor();
inline const ::std::string& APCtrlMsgSubtype_Name(APCtrlMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APCtrlMsgSubtype_descriptor(), value);
}
inline bool APCtrlMsgSubtype_Parse(
    const ::std::string& name, APCtrlMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APCtrlMsgSubtype>(
    APCtrlMsgSubtype_descriptor(), name, value);
}
enum APDataMsgSubtype {
  AP_DATA_MSG_SUBTYPE_RESERVED = 0,
  AP_DATA_MSG_SUBTYPE_ARP = 1,
  AP_DATA_MSG_SUBTYPE_DHCP = 2,
  AP_DATA_MSG_SUBTYPE_EAP = 4,
  AP_DATA_MSG_SUBTYPE_ICMP = 8,
  AP_DATA_MSG_SUBTYPE_ALL = 65535,
  APDataMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APDataMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APDataMsgSubtype_IsValid(int value);
const APDataMsgSubtype APDataMsgSubtype_MIN = AP_DATA_MSG_SUBTYPE_RESERVED;
const APDataMsgSubtype APDataMsgSubtype_MAX = AP_DATA_MSG_SUBTYPE_ALL;
const int APDataMsgSubtype_ARRAYSIZE = APDataMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APDataMsgSubtype_descriptor();
inline const ::std::string& APDataMsgSubtype_Name(APDataMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APDataMsgSubtype_descriptor(), value);
}
inline bool APDataMsgSubtype_Parse(
    const ::std::string& name, APDataMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APDataMsgSubtype>(
    APDataMsgSubtype_descriptor(), name, value);
}
enum APCiscoMsgSubtype {
  AP_CISCO_MSG_SUBTYPE_RESERVED = 0,
  AP_CISCO_MSG_SUBTYPE_NDP = 1,
  AP_CISCO_MSG_SUBTYPE_ALL = 65535,
  APCiscoMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APCiscoMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APCiscoMsgSubtype_IsValid(int value);
const APCiscoMsgSubtype APCiscoMsgSubtype_MIN = AP_CISCO_MSG_SUBTYPE_RESERVED;
const APCiscoMsgSubtype APCiscoMsgSubtype_MAX = AP_CISCO_MSG_SUBTYPE_ALL;
const int APCiscoMsgSubtype_ARRAYSIZE = APCiscoMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APCiscoMsgSubtype_descriptor();
inline const ::std::string& APCiscoMsgSubtype_Name(APCiscoMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APCiscoMsgSubtype_descriptor(), value);
}
inline bool APCiscoMsgSubtype_Parse(
    const ::std::string& name, APCiscoMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APCiscoMsgSubtype>(
    APCiscoMsgSubtype_descriptor(), name, value);
}
// ===================================================================

class APPacketHdr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:access_point.APPacketHdr) */ {
 public:
  APPacketHdr();
  virtual ~APPacketHdr();

  APPacketHdr(const APPacketHdr& from);

  inline APPacketHdr& operator=(const APPacketHdr& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketHdr& default_instance();

  enum SubtypeCase {
    kMgmt = 2,
    kCtrl = 3,
    kData = 4,
    kCisco = 5,
    SUBTYPE_NOT_SET = 0,
  };

  static const APPacketHdr* internal_default_instance();

  void Swap(APPacketHdr* other);

  // implements Message ----------------------------------------------

  inline APPacketHdr* New() const { return New(NULL); }

  APPacketHdr* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketHdr& from);
  void MergeFrom(const APPacketHdr& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketHdr* other);
  void UnsafeMergeFrom(const APPacketHdr& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .access_point.APMsgType MsgType = 1;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  ::access_point::APMsgType msgtype() const;
  void set_msgtype(::access_point::APMsgType value);

  // optional .access_point.APMgmtMsgSubtype mgmt = 2;
  private:
  bool has_mgmt() const;
  public:
  void clear_mgmt();
  static const int kMgmtFieldNumber = 2;
  ::access_point::APMgmtMsgSubtype mgmt() const;
  void set_mgmt(::access_point::APMgmtMsgSubtype value);

  // optional .access_point.APCtrlMsgSubtype ctrl = 3;
  private:
  bool has_ctrl() const;
  public:
  void clear_ctrl();
  static const int kCtrlFieldNumber = 3;
  ::access_point::APCtrlMsgSubtype ctrl() const;
  void set_ctrl(::access_point::APCtrlMsgSubtype value);

  // optional .access_point.APDataMsgSubtype data = 4;
  private:
  bool has_data() const;
  public:
  void clear_data();
  static const int kDataFieldNumber = 4;
  ::access_point::APDataMsgSubtype data() const;
  void set_data(::access_point::APDataMsgSubtype value);

  // optional .access_point.APCiscoMsgSubtype cisco = 5;
  private:
  bool has_cisco() const;
  public:
  void clear_cisco();
  static const int kCiscoFieldNumber = 5;
  ::access_point::APCiscoMsgSubtype cisco() const;
  void set_cisco(::access_point::APCiscoMsgSubtype value);

  SubtypeCase Subtype_case() const;
  // @@protoc_insertion_point(class_scope:access_point.APPacketHdr)
 private:
  inline void set_has_mgmt();
  inline void set_has_ctrl();
  inline void set_has_data();
  inline void set_has_cisco();

  inline bool has_Subtype() const;
  void clear_Subtype();
  inline void clear_has_Subtype();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int msgtype_;
  union SubtypeUnion {
    SubtypeUnion() {}
    int mgmt_;
    int ctrl_;
    int data_;
    int cisco_;
  } Subtype_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketHdr> APPacketHdr_default_instance_;

// -------------------------------------------------------------------

class APPacketsMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:access_point.APPacketsMsg) */ {
 public:
  APPacketsMsg();
  virtual ~APPacketsMsg();

  APPacketsMsg(const APPacketsMsg& from);

  inline APPacketsMsg& operator=(const APPacketsMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsMsg& default_instance();

  static const APPacketsMsg* internal_default_instance();

  void Swap(APPacketsMsg* other);

  // implements Message ----------------------------------------------

  inline APPacketsMsg* New() const { return New(NULL); }

  APPacketsMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsMsg& from);
  void MergeFrom(const APPacketsMsg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsMsg* other);
  void UnsafeMergeFrom(const APPacketsMsg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .access_point.APPacketHdr PacketHdr = 1;
  int packethdr_size() const;
  void clear_packethdr();
  static const int kPacketHdrFieldNumber = 1;
  const ::access_point::APPacketHdr& packethdr(int index) const;
  ::access_point::APPacketHdr* mutable_packethdr(int index);
  ::access_point::APPacketHdr* add_packethdr();
  ::google::protobuf::RepeatedPtrField< ::access_point::APPacketHdr >*
      mutable_packethdr();
  const ::google::protobuf::RepeatedPtrField< ::access_point::APPacketHdr >&
      packethdr() const;

  // @@protoc_insertion_point(class_scope:access_point.APPacketsMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::access_point::APPacketHdr > packethdr_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsMsg> APPacketsMsg_default_instance_;

// -------------------------------------------------------------------

class APPacketsMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:access_point.APPacketsMsgRsp) */ {
 public:
  APPacketsMsgRsp();
  virtual ~APPacketsMsgRsp();

  APPacketsMsgRsp(const APPacketsMsgRsp& from);

  inline APPacketsMsgRsp& operator=(const APPacketsMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsMsgRsp& default_instance();

  static const APPacketsMsgRsp* internal_default_instance();

  void Swap(APPacketsMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APPacketsMsgRsp* New() const { return New(NULL); }

  APPacketsMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsMsgRsp& from);
  void MergeFrom(const APPacketsMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsMsgRsp* other);
  void UnsafeMergeFrom(const APPacketsMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .access_point.APErrorStatus ErrStatus = 1;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 1;
  const ::access_point::APErrorStatus& errstatus() const;
  ::access_point::APErrorStatus* mutable_errstatus();
  ::access_point::APErrorStatus* release_errstatus();
  void set_allocated_errstatus(::access_point::APErrorStatus* errstatus);

  // optional .access_point.APPacketHdr PacketHdr = 2;
  bool has_packethdr() const;
  void clear_packethdr();
  static const int kPacketHdrFieldNumber = 2;
  const ::access_point::APPacketHdr& packethdr() const;
  ::access_point::APPacketHdr* mutable_packethdr();
  ::access_point::APPacketHdr* release_packethdr();
  void set_allocated_packethdr(::access_point::APPacketHdr* packethdr);

  // optional uint32 PacketLen = 3;
  void clear_packetlen();
  static const int kPacketLenFieldNumber = 3;
  ::google::protobuf::uint32 packetlen() const;
  void set_packetlen(::google::protobuf::uint32 value);

  // optional bytes PacketBuf = 4;
  void clear_packetbuf();
  static const int kPacketBufFieldNumber = 4;
  const ::std::string& packetbuf() const;
  void set_packetbuf(const ::std::string& value);
  void set_packetbuf(const char* value);
  void set_packetbuf(const void* value, size_t size);
  ::std::string* mutable_packetbuf();
  ::std::string* release_packetbuf();
  void set_allocated_packetbuf(::std::string* packetbuf);

  // @@protoc_insertion_point(class_scope:access_point.APPacketsMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr packetbuf_;
  ::access_point::APErrorStatus* errstatus_;
  ::access_point::APPacketHdr* packethdr_;
  ::google::protobuf::uint32 packetlen_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsMsgRsp> APPacketsMsgRsp_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// APPacketHdr

// optional .access_point.APMsgType MsgType = 1;
inline void APPacketHdr::clear_msgtype() {
  msgtype_ = 0;
}
inline ::access_point::APMsgType APPacketHdr::msgtype() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketHdr.MsgType)
  return static_cast< ::access_point::APMsgType >(msgtype_);
}
inline void APPacketHdr::set_msgtype(::access_point::APMsgType value) {
  
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketHdr.MsgType)
}

// optional .access_point.APMgmtMsgSubtype mgmt = 2;
inline bool APPacketHdr::has_mgmt() const {
  return Subtype_case() == kMgmt;
}
inline void APPacketHdr::set_has_mgmt() {
  _oneof_case_[0] = kMgmt;
}
inline void APPacketHdr::clear_mgmt() {
  if (has_mgmt()) {
    Subtype_.mgmt_ = 0;
    clear_has_Subtype();
  }
}
inline ::access_point::APMgmtMsgSubtype APPacketHdr::mgmt() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketHdr.mgmt)
  if (has_mgmt()) {
    return static_cast< ::access_point::APMgmtMsgSubtype >(Subtype_.mgmt_);
  }
  return static_cast< ::access_point::APMgmtMsgSubtype >(0);
}
inline void APPacketHdr::set_mgmt(::access_point::APMgmtMsgSubtype value) {
  if (!has_mgmt()) {
    clear_Subtype();
    set_has_mgmt();
  }
  Subtype_.mgmt_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketHdr.mgmt)
}

// optional .access_point.APCtrlMsgSubtype ctrl = 3;
inline bool APPacketHdr::has_ctrl() const {
  return Subtype_case() == kCtrl;
}
inline void APPacketHdr::set_has_ctrl() {
  _oneof_case_[0] = kCtrl;
}
inline void APPacketHdr::clear_ctrl() {
  if (has_ctrl()) {
    Subtype_.ctrl_ = 0;
    clear_has_Subtype();
  }
}
inline ::access_point::APCtrlMsgSubtype APPacketHdr::ctrl() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketHdr.ctrl)
  if (has_ctrl()) {
    return static_cast< ::access_point::APCtrlMsgSubtype >(Subtype_.ctrl_);
  }
  return static_cast< ::access_point::APCtrlMsgSubtype >(0);
}
inline void APPacketHdr::set_ctrl(::access_point::APCtrlMsgSubtype value) {
  if (!has_ctrl()) {
    clear_Subtype();
    set_has_ctrl();
  }
  Subtype_.ctrl_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketHdr.ctrl)
}

// optional .access_point.APDataMsgSubtype data = 4;
inline bool APPacketHdr::has_data() const {
  return Subtype_case() == kData;
}
inline void APPacketHdr::set_has_data() {
  _oneof_case_[0] = kData;
}
inline void APPacketHdr::clear_data() {
  if (has_data()) {
    Subtype_.data_ = 0;
    clear_has_Subtype();
  }
}
inline ::access_point::APDataMsgSubtype APPacketHdr::data() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketHdr.data)
  if (has_data()) {
    return static_cast< ::access_point::APDataMsgSubtype >(Subtype_.data_);
  }
  return static_cast< ::access_point::APDataMsgSubtype >(0);
}
inline void APPacketHdr::set_data(::access_point::APDataMsgSubtype value) {
  if (!has_data()) {
    clear_Subtype();
    set_has_data();
  }
  Subtype_.data_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketHdr.data)
}

// optional .access_point.APCiscoMsgSubtype cisco = 5;
inline bool APPacketHdr::has_cisco() const {
  return Subtype_case() == kCisco;
}
inline void APPacketHdr::set_has_cisco() {
  _oneof_case_[0] = kCisco;
}
inline void APPacketHdr::clear_cisco() {
  if (has_cisco()) {
    Subtype_.cisco_ = 0;
    clear_has_Subtype();
  }
}
inline ::access_point::APCiscoMsgSubtype APPacketHdr::cisco() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketHdr.cisco)
  if (has_cisco()) {
    return static_cast< ::access_point::APCiscoMsgSubtype >(Subtype_.cisco_);
  }
  return static_cast< ::access_point::APCiscoMsgSubtype >(0);
}
inline void APPacketHdr::set_cisco(::access_point::APCiscoMsgSubtype value) {
  if (!has_cisco()) {
    clear_Subtype();
    set_has_cisco();
  }
  Subtype_.cisco_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketHdr.cisco)
}

inline bool APPacketHdr::has_Subtype() const {
  return Subtype_case() != SUBTYPE_NOT_SET;
}
inline void APPacketHdr::clear_has_Subtype() {
  _oneof_case_[0] = SUBTYPE_NOT_SET;
}
inline APPacketHdr::SubtypeCase APPacketHdr::Subtype_case() const {
  return APPacketHdr::SubtypeCase(_oneof_case_[0]);
}
inline const APPacketHdr* APPacketHdr::internal_default_instance() {
  return &APPacketHdr_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketsMsg

// repeated .access_point.APPacketHdr PacketHdr = 1;
inline int APPacketsMsg::packethdr_size() const {
  return packethdr_.size();
}
inline void APPacketsMsg::clear_packethdr() {
  packethdr_.Clear();
}
inline const ::access_point::APPacketHdr& APPacketsMsg::packethdr(int index) const {
  // @@protoc_insertion_point(field_get:access_point.APPacketsMsg.PacketHdr)
  return packethdr_.Get(index);
}
inline ::access_point::APPacketHdr* APPacketsMsg::mutable_packethdr(int index) {
  // @@protoc_insertion_point(field_mutable:access_point.APPacketsMsg.PacketHdr)
  return packethdr_.Mutable(index);
}
inline ::access_point::APPacketHdr* APPacketsMsg::add_packethdr() {
  // @@protoc_insertion_point(field_add:access_point.APPacketsMsg.PacketHdr)
  return packethdr_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::access_point::APPacketHdr >*
APPacketsMsg::mutable_packethdr() {
  // @@protoc_insertion_point(field_mutable_list:access_point.APPacketsMsg.PacketHdr)
  return &packethdr_;
}
inline const ::google::protobuf::RepeatedPtrField< ::access_point::APPacketHdr >&
APPacketsMsg::packethdr() const {
  // @@protoc_insertion_point(field_list:access_point.APPacketsMsg.PacketHdr)
  return packethdr_;
}

inline const APPacketsMsg* APPacketsMsg::internal_default_instance() {
  return &APPacketsMsg_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketsMsgRsp

// optional .access_point.APErrorStatus ErrStatus = 1;
inline bool APPacketsMsgRsp::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline void APPacketsMsgRsp::clear_errstatus() {
  if (GetArenaNoVirtual() == NULL && errstatus_ != NULL) delete errstatus_;
  errstatus_ = NULL;
}
inline const ::access_point::APErrorStatus& APPacketsMsgRsp::errstatus() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketsMsgRsp.ErrStatus)
  return errstatus_ != NULL ? *errstatus_
                         : *::access_point::APErrorStatus::internal_default_instance();
}
inline ::access_point::APErrorStatus* APPacketsMsgRsp::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::access_point::APErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:access_point.APPacketsMsgRsp.ErrStatus)
  return errstatus_;
}
inline ::access_point::APErrorStatus* APPacketsMsgRsp::release_errstatus() {
  // @@protoc_insertion_point(field_release:access_point.APPacketsMsgRsp.ErrStatus)
  
  ::access_point::APErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline void APPacketsMsgRsp::set_allocated_errstatus(::access_point::APErrorStatus* errstatus) {
  delete errstatus_;
  errstatus_ = errstatus;
  if (errstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:access_point.APPacketsMsgRsp.ErrStatus)
}

// optional .access_point.APPacketHdr PacketHdr = 2;
inline bool APPacketsMsgRsp::has_packethdr() const {
  return this != internal_default_instance() && packethdr_ != NULL;
}
inline void APPacketsMsgRsp::clear_packethdr() {
  if (GetArenaNoVirtual() == NULL && packethdr_ != NULL) delete packethdr_;
  packethdr_ = NULL;
}
inline const ::access_point::APPacketHdr& APPacketsMsgRsp::packethdr() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketsMsgRsp.PacketHdr)
  return packethdr_ != NULL ? *packethdr_
                         : *::access_point::APPacketHdr::internal_default_instance();
}
inline ::access_point::APPacketHdr* APPacketsMsgRsp::mutable_packethdr() {
  
  if (packethdr_ == NULL) {
    packethdr_ = new ::access_point::APPacketHdr;
  }
  // @@protoc_insertion_point(field_mutable:access_point.APPacketsMsgRsp.PacketHdr)
  return packethdr_;
}
inline ::access_point::APPacketHdr* APPacketsMsgRsp::release_packethdr() {
  // @@protoc_insertion_point(field_release:access_point.APPacketsMsgRsp.PacketHdr)
  
  ::access_point::APPacketHdr* temp = packethdr_;
  packethdr_ = NULL;
  return temp;
}
inline void APPacketsMsgRsp::set_allocated_packethdr(::access_point::APPacketHdr* packethdr) {
  delete packethdr_;
  packethdr_ = packethdr;
  if (packethdr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:access_point.APPacketsMsgRsp.PacketHdr)
}

// optional uint32 PacketLen = 3;
inline void APPacketsMsgRsp::clear_packetlen() {
  packetlen_ = 0u;
}
inline ::google::protobuf::uint32 APPacketsMsgRsp::packetlen() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketsMsgRsp.PacketLen)
  return packetlen_;
}
inline void APPacketsMsgRsp::set_packetlen(::google::protobuf::uint32 value) {
  
  packetlen_ = value;
  // @@protoc_insertion_point(field_set:access_point.APPacketsMsgRsp.PacketLen)
}

// optional bytes PacketBuf = 4;
inline void APPacketsMsgRsp::clear_packetbuf() {
  packetbuf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& APPacketsMsgRsp::packetbuf() const {
  // @@protoc_insertion_point(field_get:access_point.APPacketsMsgRsp.PacketBuf)
  return packetbuf_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APPacketsMsgRsp::set_packetbuf(const ::std::string& value) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:access_point.APPacketsMsgRsp.PacketBuf)
}
inline void APPacketsMsgRsp::set_packetbuf(const char* value) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:access_point.APPacketsMsgRsp.PacketBuf)
}
inline void APPacketsMsgRsp::set_packetbuf(const void* value, size_t size) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:access_point.APPacketsMsgRsp.PacketBuf)
}
inline ::std::string* APPacketsMsgRsp::mutable_packetbuf() {
  
  // @@protoc_insertion_point(field_mutable:access_point.APPacketsMsgRsp.PacketBuf)
  return packetbuf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APPacketsMsgRsp::release_packetbuf() {
  // @@protoc_insertion_point(field_release:access_point.APPacketsMsgRsp.PacketBuf)
  
  return packetbuf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APPacketsMsgRsp::set_allocated_packetbuf(::std::string* packetbuf) {
  if (packetbuf != NULL) {
    
  } else {
    
  }
  packetbuf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), packetbuf);
  // @@protoc_insertion_point(field_set_allocated:access_point.APPacketsMsgRsp.PacketBuf)
}

inline const APPacketsMsgRsp* APPacketsMsgRsp::internal_default_instance() {
  return &APPacketsMsgRsp_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace access_point

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::access_point::APMsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::access_point::APMsgType>() {
  return ::access_point::APMsgType_descriptor();
}
template <> struct is_proto_enum< ::access_point::APMgmtMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::access_point::APMgmtMsgSubtype>() {
  return ::access_point::APMgmtMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::access_point::APCtrlMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::access_point::APCtrlMsgSubtype>() {
  return ::access_point::APCtrlMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::access_point::APDataMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::access_point::APDataMsgSubtype>() {
  return ::access_point::APDataMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::access_point::APCiscoMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::access_point::APCiscoMsgSubtype>() {
  return ::access_point::APCiscoMsgSubtype_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ap_5fpacket_2eproto__INCLUDED
