// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_packet.proto

#ifndef PROTOBUF_ap_5fpacket_2eproto__INCLUDED
#define PROTOBUF_ap_5fpacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ap_common_types.pb.h"
// @@protoc_insertion_point(includes)

namespace cheetah {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ap_5fpacket_2eproto();
void protobuf_InitDefaults_ap_5fpacket_2eproto();
void protobuf_AssignDesc_ap_5fpacket_2eproto();
void protobuf_ShutdownFile_ap_5fpacket_2eproto();

class APPacketHdr;
class APPacketsGetNotifMsg;
class APPacketsMsgRsp;
class APPacketsRegMsg;
class APPacketsRegMsgRsp;

enum APMsgType {
  AP_MSG_TYPE_RESERVED = 0,
  AP_MSG_TYPE_MGMT = 1,
  AP_MSG_TYPE_CTRL = 2,
  AP_MSG_TYPE_DATA = 3,
  AP_MSG_TYPE_CISCO = 4,
  APMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APMsgType_IsValid(int value);
const APMsgType APMsgType_MIN = AP_MSG_TYPE_RESERVED;
const APMsgType APMsgType_MAX = AP_MSG_TYPE_CISCO;
const int APMsgType_ARRAYSIZE = APMsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* APMsgType_descriptor();
inline const ::std::string& APMsgType_Name(APMsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    APMsgType_descriptor(), value);
}
inline bool APMsgType_Parse(
    const ::std::string& name, APMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APMsgType>(
    APMsgType_descriptor(), name, value);
}
enum APMgmtMsgSubtype {
  AP_MGMT_MSG_SUBTYPE_RESERVED = 0,
  AP_MGMT_MSG_SUBTYPE_ASSOC = 1,
  AP_MGMT_MSG_SUBTYPE_AUTH = 2,
  AP_MGMT_MSG_SUBTYPE_PROBE = 4,
  AP_MGMT_MSG_SUBTYPE_ALL = 65535,
  APMgmtMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APMgmtMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APMgmtMsgSubtype_IsValid(int value);
const APMgmtMsgSubtype APMgmtMsgSubtype_MIN = AP_MGMT_MSG_SUBTYPE_RESERVED;
const APMgmtMsgSubtype APMgmtMsgSubtype_MAX = AP_MGMT_MSG_SUBTYPE_ALL;
const int APMgmtMsgSubtype_ARRAYSIZE = APMgmtMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APMgmtMsgSubtype_descriptor();
inline const ::std::string& APMgmtMsgSubtype_Name(APMgmtMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APMgmtMsgSubtype_descriptor(), value);
}
inline bool APMgmtMsgSubtype_Parse(
    const ::std::string& name, APMgmtMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APMgmtMsgSubtype>(
    APMgmtMsgSubtype_descriptor(), name, value);
}
enum APCtrlMsgSubtype {
  AP_CTRL_MSG_SUBTYPE_RESERVED = 0,
  AP_CTRL_MSG_SUBTYPE_ALL = 65535,
  APCtrlMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APCtrlMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APCtrlMsgSubtype_IsValid(int value);
const APCtrlMsgSubtype APCtrlMsgSubtype_MIN = AP_CTRL_MSG_SUBTYPE_RESERVED;
const APCtrlMsgSubtype APCtrlMsgSubtype_MAX = AP_CTRL_MSG_SUBTYPE_ALL;
const int APCtrlMsgSubtype_ARRAYSIZE = APCtrlMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APCtrlMsgSubtype_descriptor();
inline const ::std::string& APCtrlMsgSubtype_Name(APCtrlMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APCtrlMsgSubtype_descriptor(), value);
}
inline bool APCtrlMsgSubtype_Parse(
    const ::std::string& name, APCtrlMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APCtrlMsgSubtype>(
    APCtrlMsgSubtype_descriptor(), name, value);
}
enum APDataMsgSubtype {
  AP_DATA_MSG_SUBTYPE_RESERVED = 0,
  AP_DATA_MSG_SUBTYPE_ARP = 1,
  AP_DATA_MSG_SUBTYPE_DHCP = 2,
  AP_DATA_MSG_SUBTYPE_EAP = 4,
  AP_DATA_MSG_SUBTYPE_ICMP = 8,
  AP_DATA_MSG_SUBTYPE_DHCPV6 = 16,
  AP_DATA_MSG_SUBTYPE_ICMPV6 = 32,
  AP_DATA_MSG_SUBTYPE_DNS = 64,
  AP_DATA_MSG_SUBTYPE_ALL = 65535,
  APDataMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APDataMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APDataMsgSubtype_IsValid(int value);
const APDataMsgSubtype APDataMsgSubtype_MIN = AP_DATA_MSG_SUBTYPE_RESERVED;
const APDataMsgSubtype APDataMsgSubtype_MAX = AP_DATA_MSG_SUBTYPE_ALL;
const int APDataMsgSubtype_ARRAYSIZE = APDataMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APDataMsgSubtype_descriptor();
inline const ::std::string& APDataMsgSubtype_Name(APDataMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APDataMsgSubtype_descriptor(), value);
}
inline bool APDataMsgSubtype_Parse(
    const ::std::string& name, APDataMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APDataMsgSubtype>(
    APDataMsgSubtype_descriptor(), name, value);
}
enum APCiscoMsgSubtype {
  AP_CISCO_MSG_SUBTYPE_RESERVED = 0,
  AP_CISCO_MSG_SUBTYPE_NDP = 1,
  AP_CISCO_MSG_SUBTYPE_ALL = 65535,
  APCiscoMsgSubtype_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APCiscoMsgSubtype_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APCiscoMsgSubtype_IsValid(int value);
const APCiscoMsgSubtype APCiscoMsgSubtype_MIN = AP_CISCO_MSG_SUBTYPE_RESERVED;
const APCiscoMsgSubtype APCiscoMsgSubtype_MAX = AP_CISCO_MSG_SUBTYPE_ALL;
const int APCiscoMsgSubtype_ARRAYSIZE = APCiscoMsgSubtype_MAX + 1;

const ::google::protobuf::EnumDescriptor* APCiscoMsgSubtype_descriptor();
inline const ::std::string& APCiscoMsgSubtype_Name(APCiscoMsgSubtype value) {
  return ::google::protobuf::internal::NameOfEnum(
    APCiscoMsgSubtype_descriptor(), value);
}
inline bool APCiscoMsgSubtype_Parse(
    const ::std::string& name, APCiscoMsgSubtype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APCiscoMsgSubtype>(
    APCiscoMsgSubtype_descriptor(), name, value);
}
// ===================================================================

class APPacketsGetNotifMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APPacketsGetNotifMsg) */ {
 public:
  APPacketsGetNotifMsg();
  virtual ~APPacketsGetNotifMsg();

  APPacketsGetNotifMsg(const APPacketsGetNotifMsg& from);

  inline APPacketsGetNotifMsg& operator=(const APPacketsGetNotifMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsGetNotifMsg& default_instance();

  static const APPacketsGetNotifMsg* internal_default_instance();

  void Swap(APPacketsGetNotifMsg* other);

  // implements Message ----------------------------------------------

  inline APPacketsGetNotifMsg* New() const { return New(NULL); }

  APPacketsGetNotifMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsGetNotifMsg& from);
  void MergeFrom(const APPacketsGetNotifMsg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsGetNotifMsg* other);
  void UnsafeMergeFrom(const APPacketsGetNotifMsg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cheetah.APPacketsGetNotifMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsGetNotifMsg> APPacketsGetNotifMsg_default_instance_;

// -------------------------------------------------------------------

class APPacketsRegMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APPacketsRegMsg) */ {
 public:
  APPacketsRegMsg();
  virtual ~APPacketsRegMsg();

  APPacketsRegMsg(const APPacketsRegMsg& from);

  inline APPacketsRegMsg& operator=(const APPacketsRegMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsRegMsg& default_instance();

  static const APPacketsRegMsg* internal_default_instance();

  void Swap(APPacketsRegMsg* other);

  // implements Message ----------------------------------------------

  inline APPacketsRegMsg* New() const { return New(NULL); }

  APPacketsRegMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsRegMsg& from);
  void MergeFrom(const APPacketsRegMsg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsRegMsg* other);
  void UnsafeMergeFrom(const APPacketsRegMsg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APRegOp Oper = 1;
  void clear_oper();
  static const int kOperFieldNumber = 1;
  ::cheetah::APRegOp oper() const;
  void set_oper(::cheetah::APRegOp value);

  // repeated .cheetah.APPacketHdr PacketHdr = 2;
  int packethdr_size() const;
  void clear_packethdr();
  static const int kPacketHdrFieldNumber = 2;
  const ::cheetah::APPacketHdr& packethdr(int index) const;
  ::cheetah::APPacketHdr* mutable_packethdr(int index);
  ::cheetah::APPacketHdr* add_packethdr();
  ::google::protobuf::RepeatedPtrField< ::cheetah::APPacketHdr >*
      mutable_packethdr();
  const ::google::protobuf::RepeatedPtrField< ::cheetah::APPacketHdr >&
      packethdr() const;

  // @@protoc_insertion_point(class_scope:cheetah.APPacketsRegMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::cheetah::APPacketHdr > packethdr_;
  int oper_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsRegMsg> APPacketsRegMsg_default_instance_;

// -------------------------------------------------------------------

class APPacketsRegMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APPacketsRegMsgRsp) */ {
 public:
  APPacketsRegMsgRsp();
  virtual ~APPacketsRegMsgRsp();

  APPacketsRegMsgRsp(const APPacketsRegMsgRsp& from);

  inline APPacketsRegMsgRsp& operator=(const APPacketsRegMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsRegMsgRsp& default_instance();

  static const APPacketsRegMsgRsp* internal_default_instance();

  void Swap(APPacketsRegMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APPacketsRegMsgRsp* New() const { return New(NULL); }

  APPacketsRegMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsRegMsgRsp& from);
  void MergeFrom(const APPacketsRegMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsRegMsgRsp* other);
  void UnsafeMergeFrom(const APPacketsRegMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APErrorStatus ErrStatus = 1;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 1;
  const ::cheetah::APErrorStatus& errstatus() const;
  ::cheetah::APErrorStatus* mutable_errstatus();
  ::cheetah::APErrorStatus* release_errstatus();
  void set_allocated_errstatus(::cheetah::APErrorStatus* errstatus);

  // optional .cheetah.APPacketsRegMsg Results = 2;
  bool has_results() const;
  void clear_results();
  static const int kResultsFieldNumber = 2;
  const ::cheetah::APPacketsRegMsg& results() const;
  ::cheetah::APPacketsRegMsg* mutable_results();
  ::cheetah::APPacketsRegMsg* release_results();
  void set_allocated_results(::cheetah::APPacketsRegMsg* results);

  // @@protoc_insertion_point(class_scope:cheetah.APPacketsRegMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::cheetah::APErrorStatus* errstatus_;
  ::cheetah::APPacketsRegMsg* results_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsRegMsgRsp> APPacketsRegMsgRsp_default_instance_;

// -------------------------------------------------------------------

class APPacketHdr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APPacketHdr) */ {
 public:
  APPacketHdr();
  virtual ~APPacketHdr();

  APPacketHdr(const APPacketHdr& from);

  inline APPacketHdr& operator=(const APPacketHdr& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketHdr& default_instance();

  enum SubtypeCase {
    kMgmt = 2,
    kCtrl = 3,
    kData = 4,
    kCisco = 5,
    SUBTYPE_NOT_SET = 0,
  };

  static const APPacketHdr* internal_default_instance();

  void Swap(APPacketHdr* other);

  // implements Message ----------------------------------------------

  inline APPacketHdr* New() const { return New(NULL); }

  APPacketHdr* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketHdr& from);
  void MergeFrom(const APPacketHdr& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketHdr* other);
  void UnsafeMergeFrom(const APPacketHdr& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APMsgType MsgType = 1;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  ::cheetah::APMsgType msgtype() const;
  void set_msgtype(::cheetah::APMsgType value);

  // optional .cheetah.APMgmtMsgSubtype mgmt = 2;
  private:
  bool has_mgmt() const;
  public:
  void clear_mgmt();
  static const int kMgmtFieldNumber = 2;
  ::cheetah::APMgmtMsgSubtype mgmt() const;
  void set_mgmt(::cheetah::APMgmtMsgSubtype value);

  // optional .cheetah.APCtrlMsgSubtype ctrl = 3;
  private:
  bool has_ctrl() const;
  public:
  void clear_ctrl();
  static const int kCtrlFieldNumber = 3;
  ::cheetah::APCtrlMsgSubtype ctrl() const;
  void set_ctrl(::cheetah::APCtrlMsgSubtype value);

  // optional .cheetah.APDataMsgSubtype data = 4;
  private:
  bool has_data() const;
  public:
  void clear_data();
  static const int kDataFieldNumber = 4;
  ::cheetah::APDataMsgSubtype data() const;
  void set_data(::cheetah::APDataMsgSubtype value);

  // optional .cheetah.APCiscoMsgSubtype cisco = 5;
  private:
  bool has_cisco() const;
  public:
  void clear_cisco();
  static const int kCiscoFieldNumber = 5;
  ::cheetah::APCiscoMsgSubtype cisco() const;
  void set_cisco(::cheetah::APCiscoMsgSubtype value);

  SubtypeCase Subtype_case() const;
  // @@protoc_insertion_point(class_scope:cheetah.APPacketHdr)
 private:
  inline void set_has_mgmt();
  inline void set_has_ctrl();
  inline void set_has_data();
  inline void set_has_cisco();

  inline bool has_Subtype() const;
  void clear_Subtype();
  inline void clear_has_Subtype();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int msgtype_;
  union SubtypeUnion {
    SubtypeUnion() {}
    int mgmt_;
    int ctrl_;
    int data_;
    int cisco_;
  } Subtype_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketHdr> APPacketHdr_default_instance_;

// -------------------------------------------------------------------

class APPacketsMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cheetah.APPacketsMsgRsp) */ {
 public:
  APPacketsMsgRsp();
  virtual ~APPacketsMsgRsp();

  APPacketsMsgRsp(const APPacketsMsgRsp& from);

  inline APPacketsMsgRsp& operator=(const APPacketsMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APPacketsMsgRsp& default_instance();

  static const APPacketsMsgRsp* internal_default_instance();

  void Swap(APPacketsMsgRsp* other);

  // implements Message ----------------------------------------------

  inline APPacketsMsgRsp* New() const { return New(NULL); }

  APPacketsMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const APPacketsMsgRsp& from);
  void MergeFrom(const APPacketsMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(APPacketsMsgRsp* other);
  void UnsafeMergeFrom(const APPacketsMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cheetah.APErrorStatus ErrStatus = 1;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 1;
  const ::cheetah::APErrorStatus& errstatus() const;
  ::cheetah::APErrorStatus* mutable_errstatus();
  ::cheetah::APErrorStatus* release_errstatus();
  void set_allocated_errstatus(::cheetah::APErrorStatus* errstatus);

  // optional .cheetah.APPacketHdr PacketHdr = 2;
  bool has_packethdr() const;
  void clear_packethdr();
  static const int kPacketHdrFieldNumber = 2;
  const ::cheetah::APPacketHdr& packethdr() const;
  ::cheetah::APPacketHdr* mutable_packethdr();
  ::cheetah::APPacketHdr* release_packethdr();
  void set_allocated_packethdr(::cheetah::APPacketHdr* packethdr);

  // optional uint32 PacketLen = 3;
  void clear_packetlen();
  static const int kPacketLenFieldNumber = 3;
  ::google::protobuf::uint32 packetlen() const;
  void set_packetlen(::google::protobuf::uint32 value);

  // optional bytes PacketBuf = 4;
  void clear_packetbuf();
  static const int kPacketBufFieldNumber = 4;
  const ::std::string& packetbuf() const;
  void set_packetbuf(const ::std::string& value);
  void set_packetbuf(const char* value);
  void set_packetbuf(const void* value, size_t size);
  ::std::string* mutable_packetbuf();
  ::std::string* release_packetbuf();
  void set_allocated_packetbuf(::std::string* packetbuf);

  // @@protoc_insertion_point(class_scope:cheetah.APPacketsMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr packetbuf_;
  ::cheetah::APErrorStatus* errstatus_;
  ::cheetah::APPacketHdr* packethdr_;
  ::google::protobuf::uint32 packetlen_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_ap_5fpacket_2eproto_impl();
  friend void  protobuf_AddDesc_ap_5fpacket_2eproto_impl();
  friend void protobuf_AssignDesc_ap_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_ap_5fpacket_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<APPacketsMsgRsp> APPacketsMsgRsp_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// APPacketsGetNotifMsg

inline const APPacketsGetNotifMsg* APPacketsGetNotifMsg::internal_default_instance() {
  return &APPacketsGetNotifMsg_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketsRegMsg

// optional .cheetah.APRegOp Oper = 1;
inline void APPacketsRegMsg::clear_oper() {
  oper_ = 0;
}
inline ::cheetah::APRegOp APPacketsRegMsg::oper() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsRegMsg.Oper)
  return static_cast< ::cheetah::APRegOp >(oper_);
}
inline void APPacketsRegMsg::set_oper(::cheetah::APRegOp value) {
  
  oper_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketsRegMsg.Oper)
}

// repeated .cheetah.APPacketHdr PacketHdr = 2;
inline int APPacketsRegMsg::packethdr_size() const {
  return packethdr_.size();
}
inline void APPacketsRegMsg::clear_packethdr() {
  packethdr_.Clear();
}
inline const ::cheetah::APPacketHdr& APPacketsRegMsg::packethdr(int index) const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsRegMsg.PacketHdr)
  return packethdr_.Get(index);
}
inline ::cheetah::APPacketHdr* APPacketsRegMsg::mutable_packethdr(int index) {
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsRegMsg.PacketHdr)
  return packethdr_.Mutable(index);
}
inline ::cheetah::APPacketHdr* APPacketsRegMsg::add_packethdr() {
  // @@protoc_insertion_point(field_add:cheetah.APPacketsRegMsg.PacketHdr)
  return packethdr_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::cheetah::APPacketHdr >*
APPacketsRegMsg::mutable_packethdr() {
  // @@protoc_insertion_point(field_mutable_list:cheetah.APPacketsRegMsg.PacketHdr)
  return &packethdr_;
}
inline const ::google::protobuf::RepeatedPtrField< ::cheetah::APPacketHdr >&
APPacketsRegMsg::packethdr() const {
  // @@protoc_insertion_point(field_list:cheetah.APPacketsRegMsg.PacketHdr)
  return packethdr_;
}

inline const APPacketsRegMsg* APPacketsRegMsg::internal_default_instance() {
  return &APPacketsRegMsg_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketsRegMsgRsp

// optional .cheetah.APErrorStatus ErrStatus = 1;
inline bool APPacketsRegMsgRsp::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline void APPacketsRegMsgRsp::clear_errstatus() {
  if (GetArenaNoVirtual() == NULL && errstatus_ != NULL) delete errstatus_;
  errstatus_ = NULL;
}
inline const ::cheetah::APErrorStatus& APPacketsRegMsgRsp::errstatus() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsRegMsgRsp.ErrStatus)
  return errstatus_ != NULL ? *errstatus_
                         : *::cheetah::APErrorStatus::internal_default_instance();
}
inline ::cheetah::APErrorStatus* APPacketsRegMsgRsp::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::cheetah::APErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsRegMsgRsp.ErrStatus)
  return errstatus_;
}
inline ::cheetah::APErrorStatus* APPacketsRegMsgRsp::release_errstatus() {
  // @@protoc_insertion_point(field_release:cheetah.APPacketsRegMsgRsp.ErrStatus)
  
  ::cheetah::APErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline void APPacketsRegMsgRsp::set_allocated_errstatus(::cheetah::APErrorStatus* errstatus) {
  delete errstatus_;
  errstatus_ = errstatus;
  if (errstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APPacketsRegMsgRsp.ErrStatus)
}

// optional .cheetah.APPacketsRegMsg Results = 2;
inline bool APPacketsRegMsgRsp::has_results() const {
  return this != internal_default_instance() && results_ != NULL;
}
inline void APPacketsRegMsgRsp::clear_results() {
  if (GetArenaNoVirtual() == NULL && results_ != NULL) delete results_;
  results_ = NULL;
}
inline const ::cheetah::APPacketsRegMsg& APPacketsRegMsgRsp::results() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsRegMsgRsp.Results)
  return results_ != NULL ? *results_
                         : *::cheetah::APPacketsRegMsg::internal_default_instance();
}
inline ::cheetah::APPacketsRegMsg* APPacketsRegMsgRsp::mutable_results() {
  
  if (results_ == NULL) {
    results_ = new ::cheetah::APPacketsRegMsg;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsRegMsgRsp.Results)
  return results_;
}
inline ::cheetah::APPacketsRegMsg* APPacketsRegMsgRsp::release_results() {
  // @@protoc_insertion_point(field_release:cheetah.APPacketsRegMsgRsp.Results)
  
  ::cheetah::APPacketsRegMsg* temp = results_;
  results_ = NULL;
  return temp;
}
inline void APPacketsRegMsgRsp::set_allocated_results(::cheetah::APPacketsRegMsg* results) {
  delete results_;
  results_ = results;
  if (results) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APPacketsRegMsgRsp.Results)
}

inline const APPacketsRegMsgRsp* APPacketsRegMsgRsp::internal_default_instance() {
  return &APPacketsRegMsgRsp_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketHdr

// optional .cheetah.APMsgType MsgType = 1;
inline void APPacketHdr::clear_msgtype() {
  msgtype_ = 0;
}
inline ::cheetah::APMsgType APPacketHdr::msgtype() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketHdr.MsgType)
  return static_cast< ::cheetah::APMsgType >(msgtype_);
}
inline void APPacketHdr::set_msgtype(::cheetah::APMsgType value) {
  
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketHdr.MsgType)
}

// optional .cheetah.APMgmtMsgSubtype mgmt = 2;
inline bool APPacketHdr::has_mgmt() const {
  return Subtype_case() == kMgmt;
}
inline void APPacketHdr::set_has_mgmt() {
  _oneof_case_[0] = kMgmt;
}
inline void APPacketHdr::clear_mgmt() {
  if (has_mgmt()) {
    Subtype_.mgmt_ = 0;
    clear_has_Subtype();
  }
}
inline ::cheetah::APMgmtMsgSubtype APPacketHdr::mgmt() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketHdr.mgmt)
  if (has_mgmt()) {
    return static_cast< ::cheetah::APMgmtMsgSubtype >(Subtype_.mgmt_);
  }
  return static_cast< ::cheetah::APMgmtMsgSubtype >(0);
}
inline void APPacketHdr::set_mgmt(::cheetah::APMgmtMsgSubtype value) {
  if (!has_mgmt()) {
    clear_Subtype();
    set_has_mgmt();
  }
  Subtype_.mgmt_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketHdr.mgmt)
}

// optional .cheetah.APCtrlMsgSubtype ctrl = 3;
inline bool APPacketHdr::has_ctrl() const {
  return Subtype_case() == kCtrl;
}
inline void APPacketHdr::set_has_ctrl() {
  _oneof_case_[0] = kCtrl;
}
inline void APPacketHdr::clear_ctrl() {
  if (has_ctrl()) {
    Subtype_.ctrl_ = 0;
    clear_has_Subtype();
  }
}
inline ::cheetah::APCtrlMsgSubtype APPacketHdr::ctrl() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketHdr.ctrl)
  if (has_ctrl()) {
    return static_cast< ::cheetah::APCtrlMsgSubtype >(Subtype_.ctrl_);
  }
  return static_cast< ::cheetah::APCtrlMsgSubtype >(0);
}
inline void APPacketHdr::set_ctrl(::cheetah::APCtrlMsgSubtype value) {
  if (!has_ctrl()) {
    clear_Subtype();
    set_has_ctrl();
  }
  Subtype_.ctrl_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketHdr.ctrl)
}

// optional .cheetah.APDataMsgSubtype data = 4;
inline bool APPacketHdr::has_data() const {
  return Subtype_case() == kData;
}
inline void APPacketHdr::set_has_data() {
  _oneof_case_[0] = kData;
}
inline void APPacketHdr::clear_data() {
  if (has_data()) {
    Subtype_.data_ = 0;
    clear_has_Subtype();
  }
}
inline ::cheetah::APDataMsgSubtype APPacketHdr::data() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketHdr.data)
  if (has_data()) {
    return static_cast< ::cheetah::APDataMsgSubtype >(Subtype_.data_);
  }
  return static_cast< ::cheetah::APDataMsgSubtype >(0);
}
inline void APPacketHdr::set_data(::cheetah::APDataMsgSubtype value) {
  if (!has_data()) {
    clear_Subtype();
    set_has_data();
  }
  Subtype_.data_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketHdr.data)
}

// optional .cheetah.APCiscoMsgSubtype cisco = 5;
inline bool APPacketHdr::has_cisco() const {
  return Subtype_case() == kCisco;
}
inline void APPacketHdr::set_has_cisco() {
  _oneof_case_[0] = kCisco;
}
inline void APPacketHdr::clear_cisco() {
  if (has_cisco()) {
    Subtype_.cisco_ = 0;
    clear_has_Subtype();
  }
}
inline ::cheetah::APCiscoMsgSubtype APPacketHdr::cisco() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketHdr.cisco)
  if (has_cisco()) {
    return static_cast< ::cheetah::APCiscoMsgSubtype >(Subtype_.cisco_);
  }
  return static_cast< ::cheetah::APCiscoMsgSubtype >(0);
}
inline void APPacketHdr::set_cisco(::cheetah::APCiscoMsgSubtype value) {
  if (!has_cisco()) {
    clear_Subtype();
    set_has_cisco();
  }
  Subtype_.cisco_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketHdr.cisco)
}

inline bool APPacketHdr::has_Subtype() const {
  return Subtype_case() != SUBTYPE_NOT_SET;
}
inline void APPacketHdr::clear_has_Subtype() {
  _oneof_case_[0] = SUBTYPE_NOT_SET;
}
inline APPacketHdr::SubtypeCase APPacketHdr::Subtype_case() const {
  return APPacketHdr::SubtypeCase(_oneof_case_[0]);
}
inline const APPacketHdr* APPacketHdr::internal_default_instance() {
  return &APPacketHdr_default_instance_.get();
}
// -------------------------------------------------------------------

// APPacketsMsgRsp

// optional .cheetah.APErrorStatus ErrStatus = 1;
inline bool APPacketsMsgRsp::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline void APPacketsMsgRsp::clear_errstatus() {
  if (GetArenaNoVirtual() == NULL && errstatus_ != NULL) delete errstatus_;
  errstatus_ = NULL;
}
inline const ::cheetah::APErrorStatus& APPacketsMsgRsp::errstatus() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsMsgRsp.ErrStatus)
  return errstatus_ != NULL ? *errstatus_
                         : *::cheetah::APErrorStatus::internal_default_instance();
}
inline ::cheetah::APErrorStatus* APPacketsMsgRsp::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::cheetah::APErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsMsgRsp.ErrStatus)
  return errstatus_;
}
inline ::cheetah::APErrorStatus* APPacketsMsgRsp::release_errstatus() {
  // @@protoc_insertion_point(field_release:cheetah.APPacketsMsgRsp.ErrStatus)
  
  ::cheetah::APErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline void APPacketsMsgRsp::set_allocated_errstatus(::cheetah::APErrorStatus* errstatus) {
  delete errstatus_;
  errstatus_ = errstatus;
  if (errstatus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APPacketsMsgRsp.ErrStatus)
}

// optional .cheetah.APPacketHdr PacketHdr = 2;
inline bool APPacketsMsgRsp::has_packethdr() const {
  return this != internal_default_instance() && packethdr_ != NULL;
}
inline void APPacketsMsgRsp::clear_packethdr() {
  if (GetArenaNoVirtual() == NULL && packethdr_ != NULL) delete packethdr_;
  packethdr_ = NULL;
}
inline const ::cheetah::APPacketHdr& APPacketsMsgRsp::packethdr() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsMsgRsp.PacketHdr)
  return packethdr_ != NULL ? *packethdr_
                         : *::cheetah::APPacketHdr::internal_default_instance();
}
inline ::cheetah::APPacketHdr* APPacketsMsgRsp::mutable_packethdr() {
  
  if (packethdr_ == NULL) {
    packethdr_ = new ::cheetah::APPacketHdr;
  }
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsMsgRsp.PacketHdr)
  return packethdr_;
}
inline ::cheetah::APPacketHdr* APPacketsMsgRsp::release_packethdr() {
  // @@protoc_insertion_point(field_release:cheetah.APPacketsMsgRsp.PacketHdr)
  
  ::cheetah::APPacketHdr* temp = packethdr_;
  packethdr_ = NULL;
  return temp;
}
inline void APPacketsMsgRsp::set_allocated_packethdr(::cheetah::APPacketHdr* packethdr) {
  delete packethdr_;
  packethdr_ = packethdr;
  if (packethdr) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:cheetah.APPacketsMsgRsp.PacketHdr)
}

// optional uint32 PacketLen = 3;
inline void APPacketsMsgRsp::clear_packetlen() {
  packetlen_ = 0u;
}
inline ::google::protobuf::uint32 APPacketsMsgRsp::packetlen() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsMsgRsp.PacketLen)
  return packetlen_;
}
inline void APPacketsMsgRsp::set_packetlen(::google::protobuf::uint32 value) {
  
  packetlen_ = value;
  // @@protoc_insertion_point(field_set:cheetah.APPacketsMsgRsp.PacketLen)
}

// optional bytes PacketBuf = 4;
inline void APPacketsMsgRsp::clear_packetbuf() {
  packetbuf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& APPacketsMsgRsp::packetbuf() const {
  // @@protoc_insertion_point(field_get:cheetah.APPacketsMsgRsp.PacketBuf)
  return packetbuf_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APPacketsMsgRsp::set_packetbuf(const ::std::string& value) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:cheetah.APPacketsMsgRsp.PacketBuf)
}
inline void APPacketsMsgRsp::set_packetbuf(const char* value) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:cheetah.APPacketsMsgRsp.PacketBuf)
}
inline void APPacketsMsgRsp::set_packetbuf(const void* value, size_t size) {
  
  packetbuf_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:cheetah.APPacketsMsgRsp.PacketBuf)
}
inline ::std::string* APPacketsMsgRsp::mutable_packetbuf() {
  
  // @@protoc_insertion_point(field_mutable:cheetah.APPacketsMsgRsp.PacketBuf)
  return packetbuf_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APPacketsMsgRsp::release_packetbuf() {
  // @@protoc_insertion_point(field_release:cheetah.APPacketsMsgRsp.PacketBuf)
  
  return packetbuf_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APPacketsMsgRsp::set_allocated_packetbuf(::std::string* packetbuf) {
  if (packetbuf != NULL) {
    
  } else {
    
  }
  packetbuf_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), packetbuf);
  // @@protoc_insertion_point(field_set_allocated:cheetah.APPacketsMsgRsp.PacketBuf)
}

inline const APPacketsMsgRsp* APPacketsMsgRsp::internal_default_instance() {
  return &APPacketsMsgRsp_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cheetah

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cheetah::APMsgType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APMsgType>() {
  return ::cheetah::APMsgType_descriptor();
}
template <> struct is_proto_enum< ::cheetah::APMgmtMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APMgmtMsgSubtype>() {
  return ::cheetah::APMgmtMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::cheetah::APCtrlMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APCtrlMsgSubtype>() {
  return ::cheetah::APCtrlMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::cheetah::APDataMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APDataMsgSubtype>() {
  return ::cheetah::APDataMsgSubtype_descriptor();
}
template <> struct is_proto_enum< ::cheetah::APCiscoMsgSubtype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APCiscoMsgSubtype>() {
  return ::cheetah::APCiscoMsgSubtype_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ap_5fpacket_2eproto__INCLUDED
