// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ap_stats.proto
// Original file comments:
// @file
// @brief Statistics RPC proto file.
//
// ----------------------------------------------------------------
//  Copyright (c) 2017 by Cisco Systems, Inc.
//  All rights reserved.
// -----------------------------------------------------------------
//
//
//
#ifndef GRPC_ap_5fstats_2eproto__INCLUDED
#define GRPC_ap_5fstats_2eproto__INCLUDED

#include "ap_stats.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace cheetah {

// @defgroup APStatistics
// @ingroup System
// Access Point Statistics.
// @{
class APStatistics final {
 public:
  static constexpr char const* service_full_name() {
    return "cheetah.APStatistics";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Get statistics
    std::unique_ptr< ::grpc::ClientReaderInterface< ::cheetah::APStatsMsgRsp>> APStatsGet(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::cheetah::APStatsMsgRsp>>(APStatsGetRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::cheetah::APStatsMsgRsp>> AsyncAPStatsGet(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::cheetah::APStatsMsgRsp>>(AsyncAPStatsGetRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::cheetah::APStatsMsgRsp>* APStatsGetRaw(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::cheetah::APStatsMsgRsp>* AsyncAPStatsGetRaw(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::cheetah::APStatsMsgRsp>> APStatsGet(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::cheetah::APStatsMsgRsp>>(APStatsGetRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::cheetah::APStatsMsgRsp>> AsyncAPStatsGet(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::cheetah::APStatsMsgRsp>>(AsyncAPStatsGetRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::cheetah::APStatsMsgRsp>* APStatsGetRaw(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request) override;
    ::grpc::ClientAsyncReader< ::cheetah::APStatsMsgRsp>* AsyncAPStatsGetRaw(::grpc::ClientContext* context, const ::cheetah::APStatsMsg& request, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_APStatsGet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Get statistics
    virtual ::grpc::Status APStatsGet(::grpc::ServerContext* context, const ::cheetah::APStatsMsg* request, ::grpc::ServerWriter< ::cheetah::APStatsMsgRsp>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_APStatsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_APStatsGet() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_APStatsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status APStatsGet(::grpc::ServerContext* context, const ::cheetah::APStatsMsg* request, ::grpc::ServerWriter< ::cheetah::APStatsMsgRsp>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAPStatsGet(::grpc::ServerContext* context, ::cheetah::APStatsMsg* request, ::grpc::ServerAsyncWriter< ::cheetah::APStatsMsgRsp>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_APStatsGet<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_APStatsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_APStatsGet() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_APStatsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status APStatsGet(::grpc::ServerContext* context, const ::cheetah::APStatsMsg* request, ::grpc::ServerWriter< ::cheetah::APStatsMsgRsp>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_APStatsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_APStatsGet() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::SplitServerStreamingHandler< ::cheetah::APStatsMsg, ::cheetah::APStatsMsgRsp>(std::bind(&WithSplitStreamingMethod_APStatsGet<BaseClass>::StreamedAPStatsGet, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_APStatsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status APStatsGet(::grpc::ServerContext* context, const ::cheetah::APStatsMsg* request, ::grpc::ServerWriter< ::cheetah::APStatsMsgRsp>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedAPStatsGet(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::cheetah::APStatsMsg,::cheetah::APStatsMsgRsp>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_APStatsGet<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_APStatsGet<Service > StreamedService;
};
// @addtogroup APStatistics
// @{
// Various RPC calls to get statistics for system, wlan, radio, etc
// /;

}  // namespace cheetah


#endif  // GRPC_ap_5fstats_2eproto__INCLUDED
