// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: ap_version.proto
// Original file comments:
// @file
// @brief Specifies the API version number
//
// ----------------------------------------------------------------
//  Copyright (c) 2016 by Cisco Systems, Inc.
//  All rights reserved.
// -----------------------------------------------------------------
//
//
//
#ifndef GRPC_ap_5fversion_2eproto__INCLUDED
#define GRPC_ap_5fversion_2eproto__INCLUDED

#include "ap_version.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace cheetah {

}  // namespace cheetah


#endif  // GRPC_ap_5fversion_2eproto__INCLUDED
