// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_version.proto

#ifndef PROTOBUF_ap_5fversion_2eproto__INCLUDED
#define PROTOBUF_ap_5fversion_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace cheetah {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ap_5fversion_2eproto();
void protobuf_InitDefaults_ap_5fversion_2eproto();
void protobuf_AssignDesc_ap_5fversion_2eproto();
void protobuf_ShutdownFile_ap_5fversion_2eproto();


enum APVersion {
  AP_VERSION_UNUSED = 0,
  AP_MAJOR_VERSION = 0,
  AP_MINOR_VERSION = 0,
  AP_SUB_VERSION = 1,
  APVersion_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  APVersion_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool APVersion_IsValid(int value);
const APVersion APVersion_MIN = AP_VERSION_UNUSED;
const APVersion APVersion_MAX = AP_SUB_VERSION;
const int APVersion_ARRAYSIZE = APVersion_MAX + 1;

const ::google::protobuf::EnumDescriptor* APVersion_descriptor();
inline const ::std::string& APVersion_Name(APVersion value) {
  return ::google::protobuf::internal::NameOfEnum(
    APVersion_descriptor(), value);
}
inline bool APVersion_Parse(
    const ::std::string& name, APVersion* value) {
  return ::google::protobuf::internal::ParseNamedEnum<APVersion>(
    APVersion_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace cheetah

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::cheetah::APVersion> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cheetah::APVersion>() {
  return ::cheetah::APVersion_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ap_5fversion_2eproto__INCLUDED
