# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_global.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ap_common_types_pb2 as ap__common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_global.proto',
  package='cheetah',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61p_global.proto\x12\x07\x63heetah\x1a\x15\x61p_common_types.proto\"?\n\tAPInitMsg\x12\x10\n\x08MajorVer\x18\x01 \x01(\r\x12\x10\n\x08MinorVer\x18\x02 \x01(\r\x12\x0e\n\x06SubVer\x18\x03 \x01(\r\"B\n\x0c\x41PInitMsgRsp\x12\x10\n\x08MajorVer\x18\x01 \x01(\r\x12\x10\n\x08MinorVer\x18\x02 \x01(\r\x12\x0e\n\x06SubVer\x18\x03 \x01(\r\"\x9f\x01\n\rAPGlobalNotif\x12-\n\tEventType\x18\x01 \x01(\x0e\x32\x1a.cheetah.APGlobalNotifType\x12)\n\tErrStatus\x18\x02 \x01(\x0b\x32\x16.cheetah.APErrorStatus\x12+\n\nInitRspMsg\x18\x03 \x01(\x0b\x32\x15.cheetah.APInitMsgRspH\x00\x42\x07\n\x05\x45vent\"\x11\n\x0f\x41PGlobalsGetMsg\"v\n\x12\x41PGlobalsGetMsgRsp\x12)\n\tErrStatus\x18\x01 \x01(\x0b\x32\x16.cheetah.APErrorStatus\x12\x1a\n\x12MaxRadioNameLength\x18\x02 \x01(\r\x12\x19\n\x11MaxSsidNameLength\x18\x03 \x01(\r*\x9c\x01\n\x11\x41PGlobalNotifType\x12!\n\x1d\x41P_GLOBAL_EVENT_TYPE_RESERVED\x10\x00\x12\x1e\n\x1a\x41P_GLOBAL_EVENT_TYPE_ERROR\x10\x01\x12\"\n\x1e\x41P_GLOBAL_EVENT_TYPE_HEARTBEAT\x10\x02\x12 \n\x1c\x41P_GLOBAL_EVENT_TYPE_VERSION\x10\x03\x32\x94\x01\n\x08\x41PGlobal\x12\x41\n\x11\x41PGlobalInitNotif\x12\x12.cheetah.APInitMsg\x1a\x16.cheetah.APGlobalNotif0\x01\x12\x45\n\x0c\x41PGlobalsGet\x12\x18.cheetah.APGlobalsGetMsg\x1a\x1b.cheetah.APGlobalsGetMsgRspb\x06proto3')
  ,
  dependencies=[ap__common__types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_APGLOBALNOTIFTYPE = _descriptor.EnumDescriptor(
  name='APGlobalNotifType',
  full_name='cheetah.APGlobalNotifType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AP_GLOBAL_EVENT_TYPE_RESERVED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AP_GLOBAL_EVENT_TYPE_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AP_GLOBAL_EVENT_TYPE_HEARTBEAT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AP_GLOBAL_EVENT_TYPE_VERSION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=486,
  serialized_end=642,
)
_sym_db.RegisterEnumDescriptor(_APGLOBALNOTIFTYPE)

APGlobalNotifType = enum_type_wrapper.EnumTypeWrapper(_APGLOBALNOTIFTYPE)
AP_GLOBAL_EVENT_TYPE_RESERVED = 0
AP_GLOBAL_EVENT_TYPE_ERROR = 1
AP_GLOBAL_EVENT_TYPE_HEARTBEAT = 2
AP_GLOBAL_EVENT_TYPE_VERSION = 3



_APINITMSG = _descriptor.Descriptor(
  name='APInitMsg',
  full_name='cheetah.APInitMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MajorVer', full_name='cheetah.APInitMsg.MajorVer', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MinorVer', full_name='cheetah.APInitMsg.MinorVer', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SubVer', full_name='cheetah.APInitMsg.SubVer', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=114,
)


_APINITMSGRSP = _descriptor.Descriptor(
  name='APInitMsgRsp',
  full_name='cheetah.APInitMsgRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MajorVer', full_name='cheetah.APInitMsgRsp.MajorVer', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MinorVer', full_name='cheetah.APInitMsgRsp.MinorVer', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SubVer', full_name='cheetah.APInitMsgRsp.SubVer', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=182,
)


_APGLOBALNOTIF = _descriptor.Descriptor(
  name='APGlobalNotif',
  full_name='cheetah.APGlobalNotif',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EventType', full_name='cheetah.APGlobalNotif.EventType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ErrStatus', full_name='cheetah.APGlobalNotif.ErrStatus', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InitRspMsg', full_name='cheetah.APGlobalNotif.InitRspMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Event', full_name='cheetah.APGlobalNotif.Event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=185,
  serialized_end=344,
)


_APGLOBALSGETMSG = _descriptor.Descriptor(
  name='APGlobalsGetMsg',
  full_name='cheetah.APGlobalsGetMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=363,
)


_APGLOBALSGETMSGRSP = _descriptor.Descriptor(
  name='APGlobalsGetMsgRsp',
  full_name='cheetah.APGlobalsGetMsgRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrStatus', full_name='cheetah.APGlobalsGetMsgRsp.ErrStatus', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxRadioNameLength', full_name='cheetah.APGlobalsGetMsgRsp.MaxRadioNameLength', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxSsidNameLength', full_name='cheetah.APGlobalsGetMsgRsp.MaxSsidNameLength', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=483,
)

_APGLOBALNOTIF.fields_by_name['EventType'].enum_type = _APGLOBALNOTIFTYPE
_APGLOBALNOTIF.fields_by_name['ErrStatus'].message_type = ap__common__types__pb2._APERRORSTATUS
_APGLOBALNOTIF.fields_by_name['InitRspMsg'].message_type = _APINITMSGRSP
_APGLOBALNOTIF.oneofs_by_name['Event'].fields.append(
  _APGLOBALNOTIF.fields_by_name['InitRspMsg'])
_APGLOBALNOTIF.fields_by_name['InitRspMsg'].containing_oneof = _APGLOBALNOTIF.oneofs_by_name['Event']
_APGLOBALSGETMSGRSP.fields_by_name['ErrStatus'].message_type = ap__common__types__pb2._APERRORSTATUS
DESCRIPTOR.message_types_by_name['APInitMsg'] = _APINITMSG
DESCRIPTOR.message_types_by_name['APInitMsgRsp'] = _APINITMSGRSP
DESCRIPTOR.message_types_by_name['APGlobalNotif'] = _APGLOBALNOTIF
DESCRIPTOR.message_types_by_name['APGlobalsGetMsg'] = _APGLOBALSGETMSG
DESCRIPTOR.message_types_by_name['APGlobalsGetMsgRsp'] = _APGLOBALSGETMSGRSP
DESCRIPTOR.enum_types_by_name['APGlobalNotifType'] = _APGLOBALNOTIFTYPE

APInitMsg = _reflection.GeneratedProtocolMessageType('APInitMsg', (_message.Message,), dict(
  DESCRIPTOR = _APINITMSG,
  __module__ = 'ap_global_pb2'
  # @@protoc_insertion_point(class_scope:cheetah.APInitMsg)
  ))
_sym_db.RegisterMessage(APInitMsg)

APInitMsgRsp = _reflection.GeneratedProtocolMessageType('APInitMsgRsp', (_message.Message,), dict(
  DESCRIPTOR = _APINITMSGRSP,
  __module__ = 'ap_global_pb2'
  # @@protoc_insertion_point(class_scope:cheetah.APInitMsgRsp)
  ))
_sym_db.RegisterMessage(APInitMsgRsp)

APGlobalNotif = _reflection.GeneratedProtocolMessageType('APGlobalNotif', (_message.Message,), dict(
  DESCRIPTOR = _APGLOBALNOTIF,
  __module__ = 'ap_global_pb2'
  # @@protoc_insertion_point(class_scope:cheetah.APGlobalNotif)
  ))
_sym_db.RegisterMessage(APGlobalNotif)

APGlobalsGetMsg = _reflection.GeneratedProtocolMessageType('APGlobalsGetMsg', (_message.Message,), dict(
  DESCRIPTOR = _APGLOBALSGETMSG,
  __module__ = 'ap_global_pb2'
  # @@protoc_insertion_point(class_scope:cheetah.APGlobalsGetMsg)
  ))
_sym_db.RegisterMessage(APGlobalsGetMsg)

APGlobalsGetMsgRsp = _reflection.GeneratedProtocolMessageType('APGlobalsGetMsgRsp', (_message.Message,), dict(
  DESCRIPTOR = _APGLOBALSGETMSGRSP,
  __module__ = 'ap_global_pb2'
  # @@protoc_insertion_point(class_scope:cheetah.APGlobalsGetMsgRsp)
  ))
_sym_db.RegisterMessage(APGlobalsGetMsgRsp)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class APGlobalStub(object):
  """@defgroup APGlobal
  @ingroup System
  Global Initialization and Notifications.
  The following RPCs are used in global initialization and capability queries.
  @{
  @addtogroup APGlobal
  @{
  /;
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.APGlobalInitNotif = channel.unary_stream(
        '/cheetah.APGlobal/APGlobalInitNotif',
        request_serializer=APInitMsg.SerializeToString,
        response_deserializer=APGlobalNotif.FromString,
        )
    self.APGlobalsGet = channel.unary_unary(
        '/cheetah.APGlobal/APGlobalsGet',
        request_serializer=APGlobalsGetMsg.SerializeToString,
        response_deserializer=APGlobalsGetMsgRsp.FromString,
        )


class APGlobalServicer(object):
  """@defgroup APGlobal
  @ingroup System
  Global Initialization and Notifications.
  The following RPCs are used in global initialization and capability queries.
  @{
  @addtogroup APGlobal
  @{
  /;
  """

  def APGlobalInitNotif(self, request, context):
    """Initialize the connection, and setup a notification channel.
    This MUST be the first call to setup the Access Point connection.

    The caller MUST maintain the notification channel to be able to
    communicate with the server.
    If this channel is not properly established and maintained, all other
    RPC requests are rejected.

    The caller must send its version information as part of the APInitMsg
    message. The server will reply with AP_GLOBAL_EVENT_TYPE_VERSION
    that tells the caller whether he can proceed or not.
    Refer to message APGlobalNotif below for further details.

    After the version handshake, the notification channel is used for
    "push" event notifications, such as:
    - APGlobalNotif.EventType = AP_GLOBAL_EVENT_TYPE_HEARTBEAT
    heartbeat notification messages are sent to the client on
    a periodic basis.
    Refer to APGlobalNotif definition for further info.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def APGlobalsGet(self, request, context):
    """Get platform specific globals
    @}
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_APGlobalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'APGlobalInitNotif': grpc.unary_stream_rpc_method_handler(
          servicer.APGlobalInitNotif,
          request_deserializer=APInitMsg.FromString,
          response_serializer=APGlobalNotif.SerializeToString,
      ),
      'APGlobalsGet': grpc.unary_unary_rpc_method_handler(
          servicer.APGlobalsGet,
          request_deserializer=APGlobalsGetMsg.FromString,
          response_serializer=APGlobalsGetMsgRsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cheetah.APGlobal', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaAPGlobalServicer(object):
  """@defgroup APGlobal
  @ingroup System
  Global Initialization and Notifications.
  The following RPCs are used in global initialization and capability queries.
  @{
  @addtogroup APGlobal
  @{
  /;
  """
  def APGlobalInitNotif(self, request, context):
    """Initialize the connection, and setup a notification channel.
    This MUST be the first call to setup the Access Point connection.

    The caller MUST maintain the notification channel to be able to
    communicate with the server.
    If this channel is not properly established and maintained, all other
    RPC requests are rejected.

    The caller must send its version information as part of the APInitMsg
    message. The server will reply with AP_GLOBAL_EVENT_TYPE_VERSION
    that tells the caller whether he can proceed or not.
    Refer to message APGlobalNotif below for further details.

    After the version handshake, the notification channel is used for
    "push" event notifications, such as:
    - APGlobalNotif.EventType = AP_GLOBAL_EVENT_TYPE_HEARTBEAT
    heartbeat notification messages are sent to the client on
    a periodic basis.
    Refer to APGlobalNotif definition for further info.
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def APGlobalsGet(self, request, context):
    """Get platform specific globals
    @}
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaAPGlobalStub(object):
  """@defgroup APGlobal
  @ingroup System
  Global Initialization and Notifications.
  The following RPCs are used in global initialization and capability queries.
  @{
  @addtogroup APGlobal
  @{
  /;
  """
  def APGlobalInitNotif(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Initialize the connection, and setup a notification channel.
    This MUST be the first call to setup the Access Point connection.

    The caller MUST maintain the notification channel to be able to
    communicate with the server.
    If this channel is not properly established and maintained, all other
    RPC requests are rejected.

    The caller must send its version information as part of the APInitMsg
    message. The server will reply with AP_GLOBAL_EVENT_TYPE_VERSION
    that tells the caller whether he can proceed or not.
    Refer to message APGlobalNotif below for further details.

    After the version handshake, the notification channel is used for
    "push" event notifications, such as:
    - APGlobalNotif.EventType = AP_GLOBAL_EVENT_TYPE_HEARTBEAT
    heartbeat notification messages are sent to the client on
    a periodic basis.
    Refer to APGlobalNotif definition for further info.
    """
    raise NotImplementedError()
  def APGlobalsGet(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Get platform specific globals
    @}
    """
    raise NotImplementedError()
  APGlobalsGet.future = None


def beta_create_APGlobal_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('cheetah.APGlobal', 'APGlobalInitNotif'): APInitMsg.FromString,
    ('cheetah.APGlobal', 'APGlobalsGet'): APGlobalsGetMsg.FromString,
  }
  response_serializers = {
    ('cheetah.APGlobal', 'APGlobalInitNotif'): APGlobalNotif.SerializeToString,
    ('cheetah.APGlobal', 'APGlobalsGet'): APGlobalsGetMsgRsp.SerializeToString,
  }
  method_implementations = {
    ('cheetah.APGlobal', 'APGlobalInitNotif'): face_utilities.unary_stream_inline(servicer.APGlobalInitNotif),
    ('cheetah.APGlobal', 'APGlobalsGet'): face_utilities.unary_unary_inline(servicer.APGlobalsGet),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_APGlobal_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('cheetah.APGlobal', 'APGlobalInitNotif'): APInitMsg.SerializeToString,
    ('cheetah.APGlobal', 'APGlobalsGet'): APGlobalsGetMsg.SerializeToString,
  }
  response_deserializers = {
    ('cheetah.APGlobal', 'APGlobalInitNotif'): APGlobalNotif.FromString,
    ('cheetah.APGlobal', 'APGlobalsGet'): APGlobalsGetMsgRsp.FromString,
  }
  cardinalities = {
    'APGlobalInitNotif': cardinality.Cardinality.UNARY_STREAM,
    'APGlobalsGet': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'cheetah.APGlobal', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
